### PR TITLE
Fix #439 Incorrect Output Voltage on CPS*EFPCLCD

### LINKED ISSUE #439: CPS: patch HID Report Descriptor to fix "output.voltage"
Observed in issue https://github.com/networkupstools/nut/issues/337#issuecomment-257284089
and on [nut-upsuser](http://lists.alioth.debian.org/pipermail/nut-upsuser/2017-June/010685.html).

Report ID 18 seems to be inheriting Logical Minimum/Logical Maximum from Report ID 16:
```
Collection(Physical)
    Report ID(16)
        Usage(LowVoltageTransfer)
        Logical Minimum(97)
        Logical Maximum(103)
        Feature(Data,Variable,Absolute)

        Usage(LowVoltageTransfer)
        Input(Constant,Variable,Absolute)

        Usage(HighVoltageTransfer)
        Logical Minimum(136)
        Logical Maximum(142)
        Feature(Data,Variable,Absolute)

        Usage(HighVoltageTransfer)
        Input(Constant,Variable,Absolute)

    Report ID(18)
        Usage(Voltage)
        Feature(Constant,Variable,Absolute)

        Report Size(8)
        Logical Minimum(0)
        Logical Maximum(255)
        Unit(SI Linear: ...)
        Unit Exponent(0)
```

I'm pretty sure this is not a bug in the NUT HID parser, but feel free to correct me. (There are other places in the CPS HID Report Descriptor that seem to mix up the locations of the parser tokens relative to Input/Output/Feature.)

### PR DESCRIPTION
**Pull request by flashydave**
This fixes the problem whereby the Output Voltage on Cyberpower CPS*EPFCLCD UPS's is masked.
The root cause is due to a legal but inappropriate Report Descriptor published as part of the HID.
Specifically it looks liike Report ID 17 was deleted (ie Report 16 is followed by Report 18) with the result that there was no attempt to reset the LogMin and LogMax values from those used by the HighVoltageTransfer Item for those used by the Output Voltage.  

The fix conditionally corrects the Report Descriptor structure by applying the same LogMin and LogMax values used by the Input Voltage Item after first checking the issue exists.  

The fix creates a generic framework for fixing Report Descriptors that can be used for different manufacturers by adding code to the appropriate subdriver rather than polluting the main code with UPS specific exceptions.

### CODE REVIEW

File: drivers/cps-hid.c [hunk 1]
```diff
@@ -262,6 +262,79 @@ static int cps_claim(HIDDevice_t *hd) {
...
+	}
+
+	upsdebugx(3, "Attempting Report Descriptor fix for UPS: Vendor:%04x, Product:%04x", vendorID, productID);
+
+	/* Apply the fix cautiously by looking for input voltage, high voltage transfer and output voltage report usages.
+	 * If the output voltage log min/max equals high voltage transfer log min/max then the bug is present.
+	 * To fix it copy the input voltage log min/max settings as reasonable values for the output voltage limits.
+	 */
+
+	if ((pData=FindReport(pDesc, 15, (PAGE_POWER_DEVICE<<16)+USAGE_VOLTAGE))) {
```
Comment (wmigas) [inline drivers/cps-hid.c:310]: I my opinion we should skip report 15 (0xe) and change output voltage:
- LogMin to 0
- LogMax leave as it is or even increase it (current value 270)

According to the [specification ](https://www.cyberpower.com/eu/pl/File/GetFileSampleByType?fileId=DS-18080023-01&fileType=Download%20Center&fileSubType=FileOriginal) for EU version of the UPS "Input Voltage Range" is "170 ~ 270". 
which means that the input voltage up to 270 V can be accepted, before system will switch to a battery.
If UPS will switch to battery I'm not sure if it will report input voltage higher than 270V, I don't have equipment to verify it.

**Comment by flashydave** [comment]
I couldnt reconcile the 270v max ac voltage specifucation of the product with
the logical min and logical max values.  My take was that they employ an
8 bit ADC on this domestic class device and it cant actually measure outside 0-255 volts.
Without access to a lab or input from cyberpower themselves its
difficult to predict its characteristics. 

It is quite possible the HID is more broken than we think and the
Min/Max values for the ConfigVoltage and Voltage (reports 0x0e and 0x0f)
are alsi in error having been inherited from report 0x0d which is
iManufacturer and defined in an earlier collection.

I would like to know the real input and output voltages (unrestricted by
internal max limits applied by the program) but dont know how best to
set it.

Maybe somebody else has more knowledge or can add something.

Happy to amend the program if it is deemed a good idea.

regards
Dave

**Comment by jimklimov** [comment]
Just in case - could the voltages be counted as an offset from a non-zero
base value? Maybe using some other report to set that base? (e.g. 170 in
one for EU, V-170 in another)?

**Comment by flashydave** [comment]
I guess that is possible but the LogMin is zero and I would expect it to
output a zero when on battery if the input had failed or been
disconnected.

I have reached our to Cyberpower and asked the question but we will have
to see if they respond in a useful way.

**Comment by flashydave** [comment]
I have received a response from Cyberpower which says they will escalate
my questions to their engineering team.  Maybe we will get clarification
as to the UPS characteristics in this area.

btw thank you for your commit.

**Comment by wmigas** [comment]
@flashydave @jimklimov may we apply changes related to the logical Max value. It should be set 
- for EU to 270 or higher . see "MAX O/P Voltage" from functional setup guide   
- for US to 144 or higher. see "MAX O/P Voltage" from functional setup guide https://dl4jz3rbrsfum.cloudfront.net/documents/CyberPower_FG_CP1500PFCLCD.pdf 
My understanding is that "MAX O/P Voltage" is the same as "UPS.Input.HighVoltageTransfer". If I'm correct, then logical Max should not be changed or should be increased, because the UPS should be able to measure higher voltage to be able to safely switch to battery, when voltage is too high.

Logical Min can be hardcoded to 0, because when there is power failure, then UPS returns 0

**Comment by jimklimov** [comment]
Just in case, CCing @nbriggs as our recent expert in USB protocol nuances, and LogMin/LogMax processing in particular.

**Comment by flashydave** [comment]
Using this logic we need to fix the InputVoltage too.

**Comment by wmigas** [comment]
> Using this logic we need to fix the InputVoltage too.

I agree with you. let's wait on CPS response. in theory voltage should be 230 +/- 15%, which gives max 264V, but in spec [they ](https://www.cyberpower.com/eu/pl/File/GetFileSampleByType?fileId=DS-18080023-01&fileType=Download%20Center&fileSubType=FileOriginal) input voltage range is 170-270. maybe it is mac which is supported by hardware. who knows

**Comment by nbriggs** [comment]
My involvement has only been with the syntactically incorrect Report Descriptors from an APC unit...

This looks like a reasonable framework for fixing the syntactically correct but logically faulty report descriptors, particularly because these errors are most likely specific to a particular manufacturer.

At the point where you're doing the fix up... I suspect you don't have access to the particular model or firmware revision level, which if so is unfortunate because it means you have to base the fix up only on an analysis of the static values in the report descriptor.

I would be interested in seeing the hex dump of the USB report descriptor from the CyberPower unit if someone would care to attach it.

I'm impressed that CyberPower is responding -- unlike the APC/Schneider Electric front line support who are still, after having seen the full decoding of the bad report description and multiple explanations, say "I see that you are having issue on the HID drivers when UPS is connected to the PC, correct?"

**Comment by wmigas** [comment]
@nbriggs 
we have access to the USBDevice_t, so we have following information:
- VendorID: 0764
- ProductID: 0501
- Manufacturer: CPS
- Product: CP1300EPFCLCD
- Serial Number: CRLJW2000151

here is an output of ` /lib/nut/usbhid-ups -DDDDDDDDDD -a cyberpower1500` 
[CP1300EPFCLCD.txt](https://github.com/networkupstools/nut/files/7786287/CP1300EPFCLCD.txt)

**Comment by flashydave** [comment]
Here is a hand decoded report:

05 84 = UPAGE Power Device
09 04 = USAGE UPS (Application collection)
a1 01 = COLLECTION Application
	09 24 = USAGE Power Summary (Logical Collection, Physical Collection)
	a1 00 = COLLECTION Physical

		85 01 = REPORT_ID 1 
		09 fe = USAGE iProduct (Static Value)
		75 08 = REPORT SIZE 8 (Global)
		95 01 = REPORT COUNT 1
		15 00 = Logical Min 0
		26 ff 00 = Logical Max 255 
		b1 23 = Feature (Constant, Variable, No Preferred),

		85 02  = REPORT_ID 2
		09 ff = USAGE iSerial (Static Value)
		b1 23 = Feature (Constant, Variable, No Preferred),

		85 1b = REPORT_ID 27 
		06 01 ff = UPAGE Vendor Defined
		09 d0 = USAGE Unknown
		b1 22 = Feature (Variable, No Preferred),

		85 03 = REPORT_ID 3 
		05 85 = UPAGE Battery System
		09 89 = USAGE iDevice Chemistry (Static Value)
		b1 23 = Feature (Constant, Variable, No Preferred),

		85 04 = REPORT_ID 4
		09 8f = USAGE iOEM Information (Static Value)
		b1 23 = Feature (Constant, Variable, No Preferred),

		85 05 = REPORT_ID 5
		09 8b = USAGE Rechargable (Static Value)
		b1 23 = Feature (Constant, Variable, No Preferred),

		85 06 = REPORT_ID 6
		09 2c = USAGE Capacity Mode (Dynamic Value)
		b1 23 = Feature (Constant, Variable, No Preferred),

		85 07 = REPORT_ID 7
		75 08 = REPORT SIZE 8 (Global)
		95 06 = REPORT COUNT 6
		25 64 = Logical Max 100
		09 83 = USAGE Design Capacity (Static Value)
		09 8d = USAGE Capacity Granularity 1 (Static Value)
		09 8e = USAGE Capacity Granularity 2 (Static Value)
		09 8c = USAGE Warning Capacity Limit (Static Value)
		09 29 = USAGE Remaining Capacity Limit (Dnamic Value)
		09 67 = USAGE Full Charge Capacity (Dynamic Value)
		b1 23 = Feature (Constant, Variable, No Preferred),

		85 08 = REPORT_ID 8
		75 08 = REPORT SIZE 8 (Global)
		95 01 = REPORT COUNT 1
		65 00 = UNIT None
		09 66 = USAGE Remaining Capacity (Dynamic Value)
		81 23 = Input (Constant, Variable, No Preferred),
		09 66 = USAGE Remaining Capacity (Dynamic Value)
		b1 a3 = Feature (Constant, Variable, No Preferred, Volatile),
		09 68 = USAGE RunTimeToEmpty
		75 10 = Report Size 16
		27 ff ff 00 00 = Logical Max 65535
		66 01 10 = UNIT Seconds
		81 23 = Input (Constant, Variable, No Preferred),
		09 68 = USAGE RunTimeToEmpty
		b1 a3 = Feature (Constant, Variable, No Preferred, Volatile),
		09 2a = USAGE RemainingTimeLimit
		26 58 02 = Logical Max 600
		81 23 = Input (Constant, Variable, No Preferred),
		09 2a = USAGE RemainingTimeLimit
		b1 a2 = Feature (Variable, No Preferred, Volatile),

		85 09 = REPORT_ID 9
		75 08 = REPORT SIZE 8 (Global)
		26 ff 00 = Logical Max 255
		05 84 = UPAGE Power Device 
		09 40 = USAGE ConfigVoltage
		67 21 d1 f0 00 = UNIT ?? Voltage V
		55 06 = EXPONENT 6 << INVALID EXPONENT
		b1 23 = Feature (Constant, Variable, No Preferred),

		85 0a = REPORT_ID 10
		09 30 = USAGE Voltage (Dynamic Value)
		b1 a3 = Feature (Constant, Variable, No Preferred, Volatile),
		09 02 = USAGE Present Status (Logical Collection)
		a1 02 = COLLECTION Logical
			65 00 = UNIT None
			55 00 = EXPONENT None

			85 0b = REPORT_ID 11
			75 01 = REPORT SIZE 1
			95 06 = REPORT COUNT 6
			25 01 = Logical Max 1
			05 85 = UPAGE Battery System
			09 d0 = USAGE ACPresent (Dynamic Flag)
			09 44 = USAGE Charging (Dynamic Flag)
			09 45 = USAGE Discharging (Dynamic Value)
			09 42 = USAGE BelowRemainingCapacityLimit (Dynamic Flag)
			09 46 = USAGE FullyCharged (Dynamic Flag)
			09 43 = USAGE RemainingTimeLimitExpired (Dynamic Flag)
			81 23 = Input (Constant, Variable, No Preferred),
			09 d0 = USAGE ACPresent
			09 44 = USAGE Charging (Dynamic Flag)
			09 45 = USAGE Discharging (Dynamic Value)
			09 42 = USAGE BelowRemainingCapacityLimit (Dynamic Flag)
			09 46 = USAGE FullyCharged (Dynamic Flag)
			09 43 = USAGE RemainingTimeLimitExpired (Dynamic Flag)
			b1 a3 = Feature (Constant, Variable, No Preferred, Volatile),
			75 02 = REPORT SIZE 2
			95 01 = REPORT COUNT 6
			81 01 = Input (Constant),
			b1 01 = Feature (Constant),
		c0 = END COLLECTION

		85 0c  = REPORT_ID 12
		05 84 = UPAGE Power Device 
		09 5a = USAGE AudibleAlarmControl
		75 08 = REPORT SIZE 8 (Global)
		15 01 = Logical Min 1
		25 03 = Logical Max 3
		b1 a2 = Feature (Variable, No Preferred, Volatile),
		09 5a  = USAGE AudibleAlarmControl
		81 22 = Input (Variable, No Preferred),

		85 0d = REPORT_ID 13
		09 fd  = USAGE iManufacturer
		15 00 = Logical Min 00
		26 ff 00 = Logical Max 255
		b1 23 = Feature (Constant, Variable, No Preferred),
	c0 = END COLLECTION
	05 84 = UPAGE Power Device
	09 1a = USAGE Input (Physical Collextion)
	a1 00 = COLLECTION Physical

		85 0e = REPORT_ID 14
		05 84 = UPAGE Power Device
		09 40 = USAGE ConfigVoltage (Static Value Dynamic Value)
		75 08 = REPORT SIZE 8 (Global)
		67 21 d1 f0 00 = UNIT AC Voltage V
		55 07 = EXPONENT 7 
		b1 23 = Feature (Constant, Variable, No Preferred),

		85 0f = REPORT_ID 15
		75 10 = Report Size 16 
		09 30 = USAGE Voltage
		b1 a3 = Feature (Constant, Variable, No Preferred, Volatile),

		85 10 = REPORT_ID 16
		09 53 = USAGE LowVoltageTransfer
		16 aa 00 = Logical Min 170
		26 b4 00 = Logical Max VALUE 180 
		b1 a2 = Feature (Variable, No Preferred, Volatile),
		09 53 = USAGE LowVoltageTransfer
		81 23 = Input (Constant, Variable, No Preferred),
		09 54 = USAGE HighVoltageTransfer
		16 04 01 = Logical Min VALUE 260
		26 0e 01 = Logical Max VALUE 270 
		b1 a2 = Feature (Variable, No Preferred, Volatile),
		09 54 = USAGE HighVoltageTransfer
		81 23 = Input (Constant, Variable, No Preferred),
	c0 = END COLLECTION
	09 1c  = USAGE Output (Physical Collection)
	a1 00 = COLLECTION Physical

		85 12 = REPORT_ID 18
		09 30 = USAGE Voltage (Dyanamic Value)
		b1 a3 = Feature (Constant, Variable, No Preferred, Volatile),
		75 08 = REPORT SIZE 8 (Global 1 byte)
		15 00 = Logical Min 0 
		26 ff 00 = Logical Max 255 
		65 00 = UNIT None
		55 00 = EXPONENT 0 

		85 13 = REPORT_ID 19
		09 35 = USAGE PercentLoad (Dynamic)
		b1 a3 = Feature (Constant, Variable, No Preferred, Volatile),

		85 14 = REPORT_ID 20
		09 58 = USAGE Test
		25 06 = Logical Max 6
		b1 a2 = Feature (Variable, No Preferred, Volatile),
		09 58 = USAGE Test (Dynamic Value)
		81 22 = Input (Variable, No Preferred),

		85 15 = REPORT_ID 21
		09 57 = USAGE DelayBeforeShutdown (Dynamic Value)
		75 10 = Report Size 16
		15 ff = Logical Min -1
		26 ff 7f = Logical Max 32767
		35 c4 = Physical Min -60
		47 c4 ff 1d 00 = Physical Max 1966020
		66 01 10 = UNIT Seconds
		b1 a2 = Feature (Variable, No Preferred, Volatile),

		85 16 = REPORT_ID 22
		09 56 = USAGE DelayBeforeStartup (Dynamic Value)
		b1 a2 = Feature (Variable, No Preferred, Volatile),

		85 17 = REPORT_ID 23
		09 6e = USAGE BOOST 
		75 01 = Report Size 1
		15 00 = Logical Min 0 
		25 01 = Logical Max 1
		35 00 = Physical Min 0
		45 00 = Physical Max 0
		65 00 = UNIT 0
		b1 a3 = Feature (Constant, Variable, No Preferred, Volatile),
		09 65 = USAGE Overload (Dynamic Flag)
		b1 a3 = Feature (Constant, Variable, No Preferred, Volatile),
		75 06 = Report Size 6
		b1 01 = Feature (Constant),

		85 18 = REPORT_ID 24
		75 10 = Report Size 16
		09 44 = USAGE ConfigActivePower (Static Value, Dynmaic Value)
		26 84 03 = Logical Max 900
		66 21 d1 = UNIT Apparent or Active Power VA 
		55 07 = EXPONENT 7 (part of unit)
		b1 a3 = Feature (Constant, Variable, No Preferred, Volatile),

		85 1a  = REPORT_ID 26
		06 01 ff = USAGE VENDOR
		65 00 = UNIT None
		55 00 = EXPONENT 0 
		75 08 = REPORT SIZE 8 (Global)
		15 00 = Logical Min 0
		25 02 = Logical Max 2
		09 43 = USAGE ConfigApparentPower (Static Value, Dynmaic Value)
		b1 a2 = Feature (Variable, No Preferred, Volatile),
		09 43 = USAGE ConfigApparentPower (Static Value, Dynmaic Value)
		81 23 = Input (Constant, Variable, No Preferred),
	c0 = END COLLECTION
c0 = END COLLECTION

**Comment by nbriggs** [comment]
Here's the machine decode (using https://github.com/abend0c1/hidrdd and the Regina-REXX-3.9.4 interpreter) -- seems to match up pretty well with your hand decode.

```
05 84        (GLOBAL) USAGE_PAGE         0x0084 Power Device Page 
09 04        (LOCAL)  USAGE              0x00840004 UPS (Application Collection)  
A1 01        (MAIN)   COLLECTION         0x01 Application (Usage=0x00840004: Page=Power Device Page, Usage=UPS, Type=Application Collection)
09 24          (LOCAL)  USAGE              0x00840024 Power Summary (Logical or Physical Collection)  
A1 00          (MAIN)   COLLECTION         0x00 Physical (Usage=0x00840024: Page=Power Device Page, Usage=Power Summary, Type=Logical or Physical Collection)
85 01            (GLOBAL) REPORT_ID          0x01 (1)  
09 FE            (LOCAL)  USAGE              0x008400FE i Product (Static Value)  
75 08            (GLOBAL) REPORT_SIZE        0x08 (8) Number of bits per field  
95 01            (GLOBAL) REPORT_COUNT       0x01 (1) Number of fields  
15 00            (GLOBAL) LOGICAL_MINIMUM    0x00 (0)  <-- Info: Consider replacing 15 00 with 14
26 FF00          (GLOBAL) LOGICAL_MAXIMUM    0x00FF (255)  
B1 23            (MAIN)   FEATURE            0x00000023 (1 field x 8 bits) 1=Constant 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 0=NonVolatile 0=Bitmap 
85 02            (GLOBAL) REPORT_ID          0x02 (2)  
09 FF            (LOCAL)  USAGE              0x008400FF i Serial Number (Static Value)  
B1 23            (MAIN)   FEATURE            0x00000023 (1 field x 8 bits) 1=Constant 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 0=NonVolatile 0=Bitmap 
85 1B            (GLOBAL) REPORT_ID          0x1B (27)  
06 01FF          (GLOBAL) USAGE_PAGE         0xFF01 Vendor-defined 
09 D0            (LOCAL)  USAGE              0xFF0100D0 <-- Warning: Undocumented usage (document it by inserting 00D0 into file FF01.conf)
B1 22            (MAIN)   FEATURE            0x00000022 (1 field x 8 bits) 0=Data 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 0=NonVolatile 0=Bitmap 
85 03            (GLOBAL) REPORT_ID          0x03 (3)  
05 85            (GLOBAL) USAGE_PAGE         0x0085 Battery System Page 
09 89            (LOCAL)  USAGE              0x00850089 i Device Chemistry (Static Value)  
B1 23            (MAIN)   FEATURE            0x00000023 (1 field x 8 bits) 1=Constant 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 0=NonVolatile 0=Bitmap 
85 04            (GLOBAL) REPORT_ID          0x04 (4)  
09 8F            (LOCAL)  USAGE              0x0085008F i OEMInformation (Static Value)  
B1 23            (MAIN)   FEATURE            0x00000023 (1 field x 8 bits) 1=Constant 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 0=NonVolatile 0=Bitmap 
85 05            (GLOBAL) REPORT_ID          0x05 (5)  
09 8B            (LOCAL)  USAGE              0x0085008B Rechargeable (Static Value)  
B1 23            (MAIN)   FEATURE            0x00000023 (1 field x 8 bits) 1=Constant 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 0=NonVolatile 0=Bitmap 
85 06            (GLOBAL) REPORT_ID          0x06 (6)  
09 2C            (LOCAL)  USAGE              0x0085002C Capacity Mode (Dynamic Value)  
B1 23            (MAIN)   FEATURE            0x00000023 (1 field x 8 bits) 1=Constant 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 0=NonVolatile 0=Bitmap 
85 07            (GLOBAL) REPORT_ID          0x07 (7)  
75 08            (GLOBAL) REPORT_SIZE        0x08 (8) Number of bits per field <-- Redundant: REPORT_SIZE is already 8 
95 06            (GLOBAL) REPORT_COUNT       0x06 (6) Number of fields  
25 64            (GLOBAL) LOGICAL_MAXIMUM    0x64 (100)  
09 83            (LOCAL)  USAGE              0x00850083 Design Capacity (Static Value)  
09 8D            (LOCAL)  USAGE              0x0085008D Capacity Granularity 1 (Static Value)  
09 8E            (LOCAL)  USAGE              0x0085008E Capacity Granularity 2 (Static Value)  
09 8C            (LOCAL)  USAGE              0x0085008C Warning Capacity Limit (Static Value)  
09 29            (LOCAL)  USAGE              0x00850029 Remaining Capacity Limit (Dynamic Value)  
09 67            (LOCAL)  USAGE              0x00850067 Full Charge Capacity (Dynamic Value)  
B1 23            (MAIN)   FEATURE            0x00000023 (6 fields x 8 bits) 1=Constant 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 0=NonVolatile 0=Bitmap 
85 08            (GLOBAL) REPORT_ID          0x08 (8)  
75 08            (GLOBAL) REPORT_SIZE        0x08 (8) Number of bits per field <-- Redundant: REPORT_SIZE is already 8 
95 01            (GLOBAL) REPORT_COUNT       0x01 (1) Number of fields  
65 00            (GLOBAL) UNIT               0x00 No unit (0=None) <-- Redundant: UNIT is already 0x00000000 <-- Info: Consider replacing 65 00 with 64
09 66            (LOCAL)  USAGE              0x00850066 Remaining Capacity (Dynamic Value)  
81 23            (MAIN)   INPUT              0x00000023 (1 field x 8 bits) 1=Constant 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 0=NonVolatile 0=Bitmap 
09 66            (LOCAL)  USAGE              0x00850066 Remaining Capacity (Dynamic Value)  
B1 A3            (MAIN)   FEATURE            0x000000A3 (1 field x 8 bits) 1=Constant 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 1=Volatile 0=Bitmap 
09 68            (LOCAL)  USAGE              0x00850068 Run Time To Empty (Dynamic Value)  
75 10            (GLOBAL) REPORT_SIZE        0x10 (16) Number of bits per field  
27 FFFF0000      (GLOBAL) LOGICAL_MAXIMUM    0x0000FFFF (65535)  
66 0110          (GLOBAL) UNIT               0x1001 Time in seconds [1 s units] (1=System=SI Linear, 1=Time=Seconds)  
81 23            (MAIN)   INPUT              0x00000023 (1 field x 16 bits) 1=Constant 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 0=NonVolatile 0=Bitmap 
09 68            (LOCAL)  USAGE              0x00850068 Run Time To Empty (Dynamic Value)  
B1 A3            (MAIN)   FEATURE            0x000000A3 (1 field x 16 bits) 1=Constant 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 1=Volatile 0=Bitmap 
09 2A            (LOCAL)  USAGE              0x0085002A Remaining Time Limit (Dynamic Value)  
26 5802          (GLOBAL) LOGICAL_MAXIMUM    0x0258 (600)  
81 23            (MAIN)   INPUT              0x00000023 (1 field x 16 bits) 1=Constant 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 0=NonVolatile 0=Bitmap 
09 2A            (LOCAL)  USAGE              0x0085002A Remaining Time Limit (Dynamic Value)  
B1 A2            (MAIN)   FEATURE            0x000000A2 (1 field x 16 bits) 0=Data 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 1=Volatile 0=Bitmap 
85 09            (GLOBAL) REPORT_ID          0x09 (9)  
75 08            (GLOBAL) REPORT_SIZE        0x08 (8) Number of bits per field  
26 FF00          (GLOBAL) LOGICAL_MAXIMUM    0x00FF (255)  
05 84            (GLOBAL) USAGE_PAGE         0x0084 Power Device Page 
09 40            (LOCAL)  USAGE              0x00840040 Config Voltage (Static Value or Dynamic Value)  
67 21D1F000      (GLOBAL) UNIT               0x00F0D121 Electric potential difference in volts [0.1 μV units] (1=System=SI Linear, 2=Length=Centimetre², 1=Mass=Gram, D=Time=Seconds⁻³, F=Current=Ampere⁻¹)  
55 06            (GLOBAL) UNIT_EXPONENT      0x06 (Unit Value x 10⁶)  
B1 23            (MAIN)   FEATURE            0x00000023 (1 field x 8 bits) 1=Constant 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 0=NonVolatile 0=Bitmap 
85 0A            (GLOBAL) REPORT_ID          0x0A (10)  
09 30            (LOCAL)  USAGE              0x00840030 Voltage (Dynamic Value)  
B1 A3            (MAIN)   FEATURE            0x000000A3 (1 field x 8 bits) 1=Constant 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 1=Volatile 0=Bitmap 
09 02            (LOCAL)  USAGE              0x00840002 Present Status (Logical Collection)  
A1 02            (MAIN)   COLLECTION         0x02 Logical (Usage=0x00840002: Page=Power Device Page, Usage=Present Status, Type=Logical Collection)
65 00              (GLOBAL) UNIT               0x00 No unit (0=None)  <-- Info: Consider replacing 65 00 with 64
55 00              (GLOBAL) UNIT_EXPONENT      0x00 (Unit Value x 10⁰)  <-- Info: Consider replacing 55 00 with 54
85 0B              (GLOBAL) REPORT_ID          0x0B (11)  
75 01              (GLOBAL) REPORT_SIZE        0x01 (1) Number of bits per field  
95 06              (GLOBAL) REPORT_COUNT       0x06 (6) Number of fields  
25 01              (GLOBAL) LOGICAL_MAXIMUM    0x01 (1)  
05 85              (GLOBAL) USAGE_PAGE         0x0085 Battery System Page 
09 D0              (LOCAL)  USAGE              0x008500D0 AC Present (Dynamic Flag)  
09 44              (LOCAL)  USAGE              0x00850044 Charging (Dynamic Flag)  
09 45              (LOCAL)  USAGE              0x00850045 Discharging (Dynamic Value)  
09 42              (LOCAL)  USAGE              0x00850042 Below Remaining Capacity Limit (Dynamic Flag)  
09 46              (LOCAL)  USAGE              0x00850046 Fully Charged (Dynamic Flag)  
09 43              (LOCAL)  USAGE              0x00850043 Remaining Time Limit Expired (Dynamic Flag)  
81 23              (MAIN)   INPUT              0x00000023 (6 fields x 1 bit) 1=Constant 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 0=NonVolatile 0=Bitmap 
09 D0              (LOCAL)  USAGE              0x008500D0 AC Present (Dynamic Flag)  
09 44              (LOCAL)  USAGE              0x00850044 Charging (Dynamic Flag)  
09 45              (LOCAL)  USAGE              0x00850045 Discharging (Dynamic Value)  
09 42              (LOCAL)  USAGE              0x00850042 Below Remaining Capacity Limit (Dynamic Flag)  
09 46              (LOCAL)  USAGE              0x00850046 Fully Charged (Dynamic Flag)  
09 43              (LOCAL)  USAGE              0x00850043 Remaining Time Limit Expired (Dynamic Flag)  
B1 A3              (MAIN)   FEATURE            0x000000A3 (6 fields x 1 bit) 1=Constant 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 1=Volatile 0=Bitmap 
75 02              (GLOBAL) REPORT_SIZE        0x02 (2) Number of bits per field  
95 01              (GLOBAL) REPORT_COUNT       0x01 (1) Number of fields  
81 01              (MAIN)   INPUT              0x00000001 (1 field x 2 bits) 1=Constant 0=Array 0=Absolute 
B1 01              (MAIN)   FEATURE            0x00000001 (1 field x 2 bits) 1=Constant 0=Array 0=Absolute 0=NoWrap 0=Linear 0=PrefState 0=NoNull 0=NonVolatile 0=Bitmap 
C0               (MAIN)   END_COLLECTION     Logical 
85 0C            (GLOBAL) REPORT_ID          0x0C (12)  
05 84            (GLOBAL) USAGE_PAGE         0x0084 Power Device Page 
09 5A            (LOCAL)  USAGE              0x0084005A Audible Alarm Control (Dynamic Value)  
75 08            (GLOBAL) REPORT_SIZE        0x08 (8) Number of bits per field  
15 01            (GLOBAL) LOGICAL_MINIMUM    0x01 (1)  
25 03            (GLOBAL) LOGICAL_MAXIMUM    0x03 (3)  
B1 A2            (MAIN)   FEATURE            0x000000A2 (1 field x 8 bits) 0=Data 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 1=Volatile 0=Bitmap 
09 5A            (LOCAL)  USAGE              0x0084005A Audible Alarm Control (Dynamic Value)  
81 22            (MAIN)   INPUT              0x00000022 (1 field x 8 bits) 0=Data 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 0=NonVolatile 0=Bitmap 
85 0D            (GLOBAL) REPORT_ID          0x0D (13)  
09 FD            (LOCAL)  USAGE              0x008400FD i Manufacturer (Static Value)  
15 00            (GLOBAL) LOGICAL_MINIMUM    0x00 (0)  <-- Info: Consider replacing 15 00 with 14
26 FF00          (GLOBAL) LOGICAL_MAXIMUM    0x00FF (255)  
B1 23            (MAIN)   FEATURE            0x00000023 (1 field x 8 bits) 1=Constant 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 0=NonVolatile 0=Bitmap 
C0             (MAIN)   END_COLLECTION     Physical 
05 84          (GLOBAL) USAGE_PAGE         0x0084 Power Device Page <-- Redundant: USAGE_PAGE is already 0x0084
09 1A          (LOCAL)  USAGE              0x0084001A Input (Physical Collection)  
A1 00          (MAIN)   COLLECTION         0x00 Physical (Usage=0x0084001A: Page=Power Device Page, Usage=Input, Type=Physical Collection)
85 0E            (GLOBAL) REPORT_ID          0x0E (14)  
05 84            (GLOBAL) USAGE_PAGE         0x0084 Power Device Page <-- Redundant: USAGE_PAGE is already 0x0084
09 40            (LOCAL)  USAGE              0x00840040 Config Voltage (Static Value or Dynamic Value)  
75 08            (GLOBAL) REPORT_SIZE        0x08 (8) Number of bits per field <-- Redundant: REPORT_SIZE is already 8 
67 21D1F000      (GLOBAL) UNIT               0x00F0D121 Electric potential difference in volts [0.1 μV units] (1=System=SI Linear, 2=Length=Centimetre², 1=Mass=Gram, D=Time=Seconds⁻³, F=Current=Ampere⁻¹)  
55 07            (GLOBAL) UNIT_EXPONENT      0x07 (Unit Value x 10⁷)  
B1 23            (MAIN)   FEATURE            0x00000023 (1 field x 8 bits) 1=Constant 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 0=NonVolatile 0=Bitmap 
85 0F            (GLOBAL) REPORT_ID          0x0F (15)  
75 10            (GLOBAL) REPORT_SIZE        0x10 (16) Number of bits per field  
09 30            (LOCAL)  USAGE              0x00840030 Voltage (Dynamic Value)  
B1 A3            (MAIN)   FEATURE            0x000000A3 (1 field x 16 bits) 1=Constant 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 1=Volatile 0=Bitmap 
85 10            (GLOBAL) REPORT_ID          0x10 (16)  
09 53            (LOCAL)  USAGE              0x00840053 Low Voltage Transfer (Dynamic Value)  
16 AA00          (GLOBAL) LOGICAL_MINIMUM    0x00AA (170)  
26 B400          (GLOBAL) LOGICAL_MAXIMUM    0x00B4 (180)  
B1 A2            (MAIN)   FEATURE            0x000000A2 (1 field x 16 bits) 0=Data 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 1=Volatile 0=Bitmap 
09 53            (LOCAL)  USAGE              0x00840053 Low Voltage Transfer (Dynamic Value)  
81 23            (MAIN)   INPUT              0x00000023 (1 field x 16 bits) 1=Constant 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 0=NonVolatile 0=Bitmap 
09 54            (LOCAL)  USAGE              0x00840054 High Voltage Transfer (Dynamic Value)  
16 0401          (GLOBAL) LOGICAL_MINIMUM    0x0104 (260)  
26 0E01          (GLOBAL) LOGICAL_MAXIMUM    0x010E (270)  
B1 A2            (MAIN)   FEATURE            0x000000A2 (1 field x 16 bits) 0=Data 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 1=Volatile 0=Bitmap 
09 54            (LOCAL)  USAGE              0x00840054 High Voltage Transfer (Dynamic Value)  
81 23            (MAIN)   INPUT              0x00000023 (1 field x 16 bits) 1=Constant 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 0=NonVolatile 0=Bitmap 
C0             (MAIN)   END_COLLECTION     Physical  <-- Warning: Physical units are still in effect PHYSICAL(MIN=,MAX=) UNIT(0x00F0D121,EXP=7)
09 1C          (LOCAL)  USAGE              0x0084001C Output (Physical Collection)  
A1 00          (MAIN)   COLLECTION         0x00 Physical (Usage=0x0084001C: Page=Power Device Page, Usage=Output, Type=Physical Collection)
85 12            (GLOBAL) REPORT_ID          0x12 (18)  
09 30            (LOCAL)  USAGE              0x00840030 Voltage (Dynamic Value)  
B1 A3            (MAIN)   FEATURE            0x000000A3 (1 field x 16 bits) 1=Constant 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 1=Volatile 0=Bitmap 
75 08            (GLOBAL) REPORT_SIZE        0x08 (8) Number of bits per field  
15 00            (GLOBAL) LOGICAL_MINIMUM    0x00 (0)  <-- Info: Consider replacing 15 00 with 14
26 FF00          (GLOBAL) LOGICAL_MAXIMUM    0x00FF (255)  
65 00            (GLOBAL) UNIT               0x00 No unit (0=None)  <-- Info: Consider replacing 65 00 with 64
55 00            (GLOBAL) UNIT_EXPONENT      0x00 (Unit Value x 10⁰)  <-- Info: Consider replacing 55 00 with 54
85 13            (GLOBAL) REPORT_ID          0x13 (19)  
09 35            (LOCAL)  USAGE              0x00840035 Percent Load (Dynamic Value)  
B1 A3            (MAIN)   FEATURE            0x000000A3 (1 field x 8 bits) 1=Constant 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 1=Volatile 0=Bitmap 
85 14            (GLOBAL) REPORT_ID          0x14 (20)  
09 58            (LOCAL)  USAGE              0x00840058 Test (Dynamic Value)  
25 06            (GLOBAL) LOGICAL_MAXIMUM    0x06 (6)  
B1 A2            (MAIN)   FEATURE            0x000000A2 (1 field x 8 bits) 0=Data 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 1=Volatile 0=Bitmap 
09 58            (LOCAL)  USAGE              0x00840058 Test (Dynamic Value)  
81 22            (MAIN)   INPUT              0x00000022 (1 field x 8 bits) 0=Data 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 0=NonVolatile 0=Bitmap 
85 15            (GLOBAL) REPORT_ID          0x15 (21)  
09 57            (LOCAL)  USAGE              0x00840057 Delay Before Shutdown (Dynamic Value)  
75 10            (GLOBAL) REPORT_SIZE        0x10 (16) Number of bits per field  
15 FF            (GLOBAL) LOGICAL_MINIMUM    0xFF (-1)  
26 FF7F          (GLOBAL) LOGICAL_MAXIMUM    0x7FFF (32767)  
35 C4            (GLOBAL) PHYSICAL_MINIMUM   0xC4 (-60)  
47 C4FF1D00      (GLOBAL) PHYSICAL_MAXIMUM   0x001DFFC4 (1966020)  
66 0110          (GLOBAL) UNIT               0x1001 Time in seconds [1 s units] (1=System=SI Linear, 1=Time=Seconds)  
B1 A2            (MAIN)   FEATURE            0x000000A2 (1 field x 16 bits) 0=Data 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 1=Volatile 0=Bitmap 
85 16            (GLOBAL) REPORT_ID          0x16 (22)  
09 56            (LOCAL)  USAGE              0x00840056 Delay Before Startup (Dynamic Value)  
B1 A2            (MAIN)   FEATURE            0x000000A2 (1 field x 16 bits) 0=Data 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 1=Volatile 0=Bitmap 
85 17            (GLOBAL) REPORT_ID          0x17 (23)  
09 6E            (LOCAL)  USAGE              0x0084006E Boost (Dynamic Flag)  
75 01            (GLOBAL) REPORT_SIZE        0x01 (1) Number of bits per field  
15 00            (GLOBAL) LOGICAL_MINIMUM    0x00 (0)  <-- Info: Consider replacing 15 00 with 14
25 01            (GLOBAL) LOGICAL_MAXIMUM    0x01 (1)  
35 00            (GLOBAL) PHYSICAL_MINIMUM   0x00 (0)  <-- Info: Consider replacing 35 00 with 34
45 00            (GLOBAL) PHYSICAL_MAXIMUM   0x00 (0)  <-- Info: Consider replacing 45 00 with 44
65 00            (GLOBAL) UNIT               0x00 No unit (0=None)  <-- Info: Consider replacing 65 00 with 64
B1 A3            (MAIN)   FEATURE            0x000000A3 (1 field x 1 bit) 1=Constant 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 1=Volatile 0=Bitmap 
09 65            (LOCAL)  USAGE              0x00840065 Overload (Dynamic Flag)  
B1 A3            (MAIN)   FEATURE            0x000000A3 (1 field x 1 bit) 1=Constant 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 1=Volatile 0=Bitmap 
75 06            (GLOBAL) REPORT_SIZE        0x06 (6) Number of bits per field  
B1 01            (MAIN)   FEATURE            0x00000001 (1 field x 6 bits) 1=Constant 0=Array 0=Absolute 0=NoWrap 0=Linear 0=PrefState 0=NoNull 0=NonVolatile 0=Bitmap 
85 18            (GLOBAL) REPORT_ID          0x18 (24)  
75 10            (GLOBAL) REPORT_SIZE        0x10 (16) Number of bits per field  
09 44            (LOCAL)  USAGE              0x00840044 Config Active Power (Static Value or Dynamic Value)  
26 8403          (GLOBAL) LOGICAL_MAXIMUM    0x0384 (900)  
66 21D1          (GLOBAL) UNIT               0xD121 Power in watts [0.1 μW units] (1=System=SI Linear, 2=Length=Centimetre², 1=Mass=Gram, D=Time=Seconds⁻³)  
55 07            (GLOBAL) UNIT_EXPONENT      0x07 (Unit Value x 10⁷)  
B1 A3            (MAIN)   FEATURE            0x000000A3 (1 field x 16 bits) 1=Constant 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 1=Volatile 0=Bitmap 
85 1A            (GLOBAL) REPORT_ID          0x1A (26)  
06 01FF          (GLOBAL) USAGE_PAGE         0xFF01 Vendor-defined 
65 00            (GLOBAL) UNIT               0x00 No unit (0=None)  <-- Info: Consider replacing 65 00 with 64
55 00            (GLOBAL) UNIT_EXPONENT      0x00 (Unit Value x 10⁰)  <-- Info: Consider replacing 55 00 with 54
75 08            (GLOBAL) REPORT_SIZE        0x08 (8) Number of bits per field  
15 00            (GLOBAL) LOGICAL_MINIMUM    0x00 (0) <-- Redundant: LOGICAL_MINIMUM is already 0 <-- Info: Consider replacing 15 00 with 14
25 02            (GLOBAL) LOGICAL_MAXIMUM    0x02 (2)  
09 43            (LOCAL)  USAGE              0xFF010043 <-- Warning: Undocumented usage (document it by inserting 0043 into file FF01.conf)
B1 A2            (MAIN)   FEATURE            0x000000A2 (1 field x 8 bits) 0=Data 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 1=Volatile 0=Bitmap 
09 43            (LOCAL)  USAGE              0xFF010043 <-- Warning: Undocumented usage (document it by inserting 0043 into file FF01.conf)
81 23            (MAIN)   INPUT              0x00000023 (1 field x 8 bits) 1=Constant 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 0=NonVolatile 0=Bitmap 
C0             (MAIN)   END_COLLECTION     Physical 
85 1C          (GLOBAL) REPORT_ID          0x1C (28)  
09 BA          (LOCAL)  USAGE              0xFF0100BA <-- Warning: Undocumented usage (document it by inserting 00BA into file FF01.conf)
A1 02          (MAIN)   COLLECTION         0x02 Logical (Usage=0xFF0100BA: Page=Vendor-defined, Usage=, Type=) <-- Error: COLLECTION must be preceded by a known USAGE
75 10            (GLOBAL) REPORT_SIZE        0x10 (16) Number of bits per field  
27 FFFF0000      (GLOBAL) LOGICAL_MAXIMUM    0x0000FFFF (65535)  
09 BB            (LOCAL)  USAGE              0xFF0100BB <-- Warning: Undocumented usage (document it by inserting 00BB into file FF01.conf)
B1 22            (MAIN)   FEATURE            0x00000022 (1 field x 16 bits) 0=Data 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 0=NonVolatile 0=Bitmap 
75 08            (GLOBAL) REPORT_SIZE        0x08 (8) Number of bits per field  
26 FF00          (GLOBAL) LOGICAL_MAXIMUM    0x00FF (255)  
09 BC            (LOCAL)  USAGE              0xFF0100BC <-- Warning: Undocumented usage (document it by inserting 00BC into file FF01.conf)
B1 22            (MAIN)   FEATURE            0x00000022 (1 field x 8 bits) 0=Data 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 0=NonVolatile 0=Bitmap 
75 10            (GLOBAL) REPORT_SIZE        0x10 (16) Number of bits per field  
27 FFFF0000      (GLOBAL) LOGICAL_MAXIMUM    0x0000FFFF (65535)  
09 BD            (LOCAL)  USAGE              0xFF0100BD <-- Warning: Undocumented usage (document it by inserting 00BD into file FF01.conf)
B2 A201          (MAIN)   FEATURE            0x000001A2 (1 field x 16 bits) 0=Data 1=Variable 0=Absolute 0=NoWrap 0=Linear 1=NoPrefState 0=NoNull 1=Volatile 1=Buffer 
C0             (MAIN)   END_COLLECTION     Logical 
C0           (MAIN)   END_COLLECTION     Application 
```

**Comment by flashydave** [comment]
Here is CyberPower's response:
"This is an update regarding your CPS900EFPCLCD. Please be advised that
UPS
will report the voltage above 255V(even 270V), some software will limit   
the maximum voltage according to the declared range of the input
voltage, 
which is 255. On the UPS, once the voltage is above 255V, AVR will
enable 
to buck the input voltage. Additionally, the UPS model misreports the     
battery voltage as 24v when there is only one 12v cell fitted, please be  
advised that this has been fixed in the latest firmware version of the    
UPS."

Given the value reurned as actually a 16 bit number I guess we could set
a very high logmax setting - they imply even above 270.  I doubt it
would cause any erroneous operation as far as the driver is concerned.

Re the misreporting of the battery voltage I have asked what rev it was
fixed in. However I am not sure we get that info via the HID (although
their GUI software reports it. Maybe its one of the vendor unique
commands - I have a USB packet capture I might try to use to work it out)

**Comment by jimklimov** [comment]
Note: updated with the current state of the NUT master branch (since recently including the libusb-1.0(+0.1) codebase as well), to solve a merge conflict and to safely forget the sibling PR originally posted with libusb-1.0 as the target.

**Comment by flashydave** [comment]
Not sure why the jenkins CI seems to be stalled. Can someone take a look?
The pull request is otherwise complete and ready for merging.

**Comment by jimklimov** [comment]
My condolences about that delay. The Fosshost VMs used for the
multiplatform NUT CI farm had migrated over the end of year, to weaker
machines it seems, but ones at least available (sponsor change). And then
libusb-1.0 support layers landed, including some bug-fixes (and increased
default sensitivity to warnings), so "ephemeral branches" for ~30 not yet
merged PRs got recalculated. So now it is unclogging that queue, slowly...
so we'd see the proposed code and recipes remain good everywhere.

**Comment by jimklimov** [comment]
Note: after recent clean-up in master branch and related bump of warnings sensitivity (and required non-regression), this PR is now seen to introduce some issues to fix first:

````
--- cps-hid.o ---
depbase=`echo cps-hid.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; /usr/lib/ccache/clang-10 -DHAVE_CONFIG_H -I. -I../include    -I/usr/home/abuild/jenkins-nut/workspace/nut_nut_PR-1245@2/tmp/include -I../include  -I/usr/local/include/neon  -I/usr/local/include -I/usr/local/include -I/usr/local/include/modbus -I/usr/home/abuild/jenkins-nut/workspace/nut_nut_PR-1245@2/tmp/include -std=gnu17 -m64 -Qunused-arguments -fdiagnostics-color=always -Wno-unknown-warning-option -std=gnu99 -ferror-limit=0 -Wno-system-headers -Wall -Wextra -Weverything -Wno-disabled-macro-expansion -Wno-unused-macros -Wno-reserved-id-macro -Wno-padded -Wno-documentation -Wno-cast-qual -pedantic -Wno-float-conversion -Wno-double-promotion -Wno-implicit-float-conversion -Wno-conversion -Wno-incompatible-pointer-types-discards-qualifiers -Werror -MT cps-hid.o -MD -MP -MF $depbase.Tpo -c -o cps-hid.o cps-hid.c && mv -f $depbase.Tpo $depbase.Po

--- cps-hid.o ---
[1mcps-hid.c:279:34: [0m[0;1;31merror: [0m[1mdeclaration shadows a variable in the global scope [-Werror,-Wshadow][0m
HIDData_t *FindReport(HIDDesc_t *pDesc, uint8_t ReportID, HIDNode_t node)
[0;1;32m                                 ^
[0m[1m./libhid.h:81:19: [0m[0;1;30mnote: [0mprevious declaration is here[0m
extern HIDDesc_t        *pDesc; /* parsed Report Descriptor */
[0;1;32m                         ^
[0m[1mcps-hid.c:279:12: [0m[0;1;31merror: [0m[1mno previous prototype for function 'FindReport' [-Werror,-Wmissing-prototypes][0m
HIDData_t *FindReport(HIDDesc_t *pDesc, uint8_t ReportID, HIDNode_t node)
[0;1;32m           ^
[0m[1mcps-hid.c:279:1: [0m[0;1;30mnote: [0mdeclare 'static' if the function is not intended to be used outside of this translation unit[0m
HIDData_t *FindReport(HIDDesc_t *pDesc, uint8_t ReportID, HIDNode_t node)
[0;1;32m^
[0m[0;32mstatic 
[0m[1mcps-hid.c:302:62: [0m[0;1;31merror: [0m[1mdeclaration shadows a variable in the global scope [-Werror,-Wshadow][0m
static int cps_fix_report_desc(HIDDevice_t *pDev, HIDDesc_t *pDesc) {
[0;1;32m                                                             ^
[0m[1m./libhid.h:81:19: [0m[0;1;30mnote: [0mprevious declaration is here[0m
extern HIDDesc_t        *pDesc; /* parsed Report Descriptor */
[0;1;32m                         ^
[0m3 errors generated.
*** [cps-hid.o] Error code 1
````

UPDATE: Sorry about ANSI formatting chars in that stream

**Comment by flashydave** [comment]
Trivially easy to fix the name clash, the other is unrelated to me but seems easy too.  Are you going to fix on my behalf or do you want me to do it?

**Comment by jimklimov** [comment]
Thanks for the offer, I think I can handle these CI nits now, anyhow already checked out the branch to reproduce the issue and re-post without ANSI formatting :)

**Comment by jimklimov** [comment]
I suppose inspiration from `hidparser.c` could have misfired here; I'll pre-emptively reword that too, to avoid stepping into this twice :)

**Comment by jimklimov** [comment]
Hooray, finally good enough for the (stuttering lately) CI farm!

**Comment by nbriggs** [comment]
at https://ci.networkupstools.org/blue/organizations/jenkins/nut%2Fnut/detail/PR-1245/15/pipeline it shows one failure for 
"jenkins-freebsd12-worker was marked offline: Connection was broken: java.io.EOFException"

Don't know anything about the details of your setup, but perhaps there's a (virtual) machine not running properly?

**Comment by jimklimov** [comment]
Sadly yes, things got a bit derailed by Fosshost migration of NUT CI VMs to
another sponsor, that are weaker than the old farm, so it seems we
occasionally hit timeouts somewhere in Jenkins or networking in general,
perhaps losing heartbeats. Feels like those VMs use RAM from swapspace on
host...
