### PR TITLE
drivers/nutdrv_qx.c: improve Armac subdriver

### LINKED ISSUE #1978: Problem with  NUTDRV_QX, subdriver  armac - unable start driver
Hello

I have this UPS  http://armac.pl/oferta/ups-office-line-interactive-o850elcd/

I compiled the latest nut-2.8.0 from sources  from file [nut-2.8.0.tar.gz](https://www.networkupstools.org/source/2.8/nut-2.8.0.tar.gz)

Here is my lsusb output:

```
Bus 008 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 005 Device 002: ID 2357:0120 TP-Link Archer T2U PLUS [RTL8821AU]
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 007 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 006 Device 002: ID 0925:1234 Lakeview Research UPS USB MON V1.4
Bus 006 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub



```

Then I try this settings in ups.conf :

```
[poddasze]
    driver = nutdrv_qx
    port   = auto
    vendorid = 0925
    productid = 1234
    subdriver ="armac"
    product = "UPS USB MON V1.4"
    bus = "006"

```

But when I try   upsdrvctl start I get:

```
Network UPS Tools - UPS driver controller 2.8.0
Network UPS Tools - Generic Q* USB/Serial driver 0.32 (2.8.0)
USB communication driver (libusb 1.0) 0.43
 upsdrvctl startUsing protocol: Megatec 0.06
Can't initialise data from the UPS
Driver failed to start (exit status=1)


```
So I try to discover more and run   ./nutdrv_qx -DDD -a poddasze and get :

```
Network UPS Tools - Generic Q* USB/Serial driver 0.32 (2.8.0)
USB communication driver (libusb 1.0) 0.43
   0.000000     [D3] do_global_args: var='maxretry' val='3'
   0.000953     [D3] main_arg: var='driver' val='nutdrv_qx'
   0.001053     [D3] main_arg: var='port' val='auto'
   0.001157     [D3] main_arg: var='vendorid' val='0925'
   0.001255     [D3] main_arg: var='productid' val='1234'
   0.001351     [D3] main_arg: var='subdriver' val='armac'
   0.001448     [D3] main_arg: var='product' val='UPS USB MON V1.4'
   0.001536     [D3] main_arg: var='bus' val='006'
   0.001699     [D1] debug level is '3'
   0.003620     [D1] upsdrv_initups...
   0.085404     [D2] Checking device 1 of 10 (1D6B/0001)
   0.085827     [D1] Failed to open device (1D6B/0001), skipping: Access denied (insufficient permissions)
   0.085941     [D2] Checking device 2 of 10 (2357/0120)
   0.086079     [D1] Failed to open device (2357/0120), skipping: Access denied (insufficient permissions)
   0.086163     [D2] Checking device 3 of 10 (1D6B/0002)
   0.086289     [D1] Failed to open device (1D6B/0002), skipping: Access denied (insufficient permissions)
   0.086365     [D2] Checking device 4 of 10 (1D6B/0001)
   0.086485     [D1] Failed to open device (1D6B/0001), skipping: Access denied (insufficient permissions)
   0.086560     [D2] Checking device 5 of 10 (1D6B/0002)
   0.086683     [D1] Failed to open device (1D6B/0002), skipping: Access denied (insufficient permissions)
   0.086755     [D2] Checking device 6 of 10 (0925/1234)
   0.095368     [D2] - VendorID: 0925
   0.095425     [D2] - ProductID: 1234
   0.095456     [D2] - Manufacturer: ?
   0.095484     [D2] - Product: UPS USB MON V1.4
   0.095511     [D2] - Serial Number: unknown
   0.095542     [D2] - Bus: 006
   0.095568     [D2] - Device: unknown
   0.095593     [D2] - Device release number: 0001
   0.095618     [D2] Trying to match device
   0.095649     [D3] match_function_regex: matching a device...
   0.096184     [D2] Device matches
   0.096234     [D2] Reading first configuration descriptor
   0.096300     [D3] libusb_kernel_driver_active() returned 0
   0.096413     [D2] Claimed interface 0 successfully
   0.096457     [D3] nut_usb_set_altinterface: skipped libusb_set_interface_alt_setting(udev, 0, 0)
   0.096551     [D2] armac: unsupported cmd: QGS
   0.096596     [D2] qx_process_answer: short reply (input.voltage)
   0.096632     [D2] armac: unsupported cmd: QGS
   0.096664     [D2] qx_process_answer: short reply (input.voltage)
   0.096697     [D2] armac: unsupported cmd: QGS
   0.096774     [D2] qx_process_answer: short reply (input.voltage)
   0.096822     [D2] armac: unsupported cmd: M
   0.096859     [D2] voltronic_qs_protocol: invalid protocol [M]
   0.096891     [D2] armac: unsupported cmd: M
   0.096925     [D2] voltronic_qs_protocol: invalid protocol [M]
   0.096957     [D2] armac: unsupported cmd: M
   0.096990     [D2] voltronic_qs_protocol: invalid protocol [M]
   0.097022     [D2] armac: unsupported cmd: M
   0.097060     [D2] voltronic_qs_hex_protocol: invalid protocol [M]
   0.097092     [D2] armac: unsupported cmd: M
   0.097127     [D2] voltronic_qs_hex_protocol: invalid protocol [M]
   0.097160     [D2] armac: unsupported cmd: M
   0.097193     [D2] voltronic_qs_hex_protocol: invalid protocol [M]
   0.097225     [D2] armac: unsupported cmd: QS
   0.097258     [D2] qx_process_answer: short reply (input.voltage)
   0.097289     [D2] armac: unsupported cmd: QS
   0.097320     [D2] qx_process_answer: short reply (input.voltage)
   0.097350     [D2] armac: unsupported cmd: QS
   0.097381     [D2] qx_process_answer: short reply (input.voltage)
   0.097413     [D2] armac: unsupported cmd: D
   0.097444     [D2] qx_process_answer: short reply (input.voltage)
   0.097476     [D2] armac: unsupported cmd: D
   0.097507     [D2] qx_process_answer: short reply (input.voltage)
   0.097538     [D2] armac: unsupported cmd: D
   0.097568     [D2] qx_process_answer: short reply (input.voltage)
   1.306422     [D3] armac command Q1 response read: '(230.0 000.0 233.0 008 49.0 13.7 30.8 00001'
   2.494469     [D3] armac command ID response read: '#                           V2.63     '
   3.702449     [D3] armac command Q1 response read: '(231.0 000.0 232.0 008 49.0 13.7 30.8 00001'
   4.890439     [D3] armac command ID response read: '#                           V2.63     '
   6.098435     [D3] armac command Q1 response read: '(231.0 000.0 233.0 009 49.0 13.7 30.8 00001'
   7.287404     [D3] armac command ID response read: '#                           V2.63     '
   8.495400     [D3] armac command Q1 response read: '(228.0 000.0 231.0 008 49.0 13.7 30.8 00001'
   8.495640     [D2] armac: unsupported cmd: QPI
   8.495718     [D2] qx_process_answer: short reply (ups.firmware.aux)
   9.713366     [D3] armac command Q1 response read: '(229.0 000.0 231.0 008 49.0 13.7 30.8 00001'
   9.713591     [D2] armac: unsupported cmd: QPI
   9.713670     [D2] qx_process_answer: short reply (ups.firmware.aux)
  10.931370     [D3] armac command Q1 response read: '(229.0 000.0 230.0 009 50.0 13.7 30.8 00001'
  10.931597     [D2] armac: unsupported cmd: QPI
  10.931674     [D2] qx_process_answer: short reply (ups.firmware.aux)
  12.149365     [D3] armac command Q1 response read: '(231.0 000.0 233.0 009 49.0 13.7 30.8 00001'
  13.337335     [D3] armac command I response read: '#                           V2.63     '
  13.337526     Using protocol: Megatec 0.06
  13.337683     [D1] upsdrv_initinfo...
  14.555319     [D3] armac command Q1 response read: '(231.0 000.0 233.0 008 49.0 13.7 30.8 00001'
  14.555554     [D2] qx_process_answer: short reply (output.voltage)
  14.555647     [D2] qx_process_answer: short reply (ups.load)
  14.555724     [D2] qx_process_answer: short reply (input.frequency)
  14.555801     [D2] qx_process_answer: short reply (battery.voltage)
  14.555880     [D2] qx_process_answer: short reply (ups.temperature)
  14.555955     [D2] qx_process_answer: short reply (ups.status)
  14.556023     Can't initialise data from the UPS
  14.556091     [D1] upsdrv_cleanup...
```

So it get some data about voltages  , but not enought to start the driver :( 

Please help

### PR DESCRIPTION
**Pull request by blaa**
Based on a debug output from a newer device (*/PF1) we've improved understanding on how:
- those devices encode the length of a chunk of data.
- how the end of transmission can be marked / detected.

Related to:
https://github.com/networkupstools/nut/pull/2003
https://github.com/networkupstools/nut/issues/1978

Closes #1978 

I'll test this changes for "old" devices in september. *Maybe* earlier.

### CODE REVIEW

File: drivers/nutdrv_qx.c [hunk 1]
```diff
@@ -1838,20 +1842,45 @@ static int	armac_command(const char *cmd, char *buf, size_t buflen)
...
+		 */
 		bytes_available = (unsigned char)tmpbuf[0] & 0x0f;
 		if (bytes_available == 0) {
 			/* End of transfer */
 			break;
 		}
 
-		memcpy(buf + bufpos, tmpbuf + 1, bytes_available);
-		bufpos += bytes_available;
+		if (bytes_available > READ_SIZE - 1) {
```
Comment (jimklimov) [inline drivers/nutdrv_qx.c:1859]: So after all, `READ_SIZE - 1` or `ret -1`, pedantically? Currently they are checked to be same, but in the possible future? Logically?..

File: drivers/nutdrv_qx.c [hunk 2]
```diff
@@ -1838,20 +1842,45 @@ static int	armac_command(const char *cmd, char *buf, size_t buflen)
...
+			/* Single interrupt transfer has 1 control + 5 data bytes */
+			bytes_available = READ_SIZE - 1;
+		}
+
+		/* Copy bytes into the final buffer while detecting end of line - \r */
+		for (size_t i = 0; i < bytes_available; i++) {
```
Comment (jimklimov) [inline drivers/nutdrv_qx.c:1865]: `i` already declared on top, "shadowed" here for no gain?

File: drivers/nutdrv_qx.c [hunk 3]
```diff
@@ -1838,20 +1842,45 @@ static int	armac_command(const char *cmd, char *buf, size_t buflen)
...
+			buf[bufpos++] = tmpbuf[i + 1];
+			if (tmpbuf[i + 1] == 0x0d) {
+				if (i + 1 != bytes_available) {
+					upsdebugx(3, "trailing bytes in serial transmission found: %lu copied out of %lu",
```
Comment (jimklimov) [inline drivers/nutdrv_qx.c:1869]: `%" PRIuSIZE` not `%lu` technically to be clean, not without casting ;)

May need `nut_stdint.h` if not there yet (unlikely).

**Review by jimklimov — CHANGES_REQUESTED** [review]
Thanks for the refinement! Some comments posted.

File: drivers/nutdrv_qx.c (hunk 1 above)
Comment (blaa) [reply drivers/nutdrv_qx.c:1859]: I believe the READ_SIZE is more explicit. ret just checks the return value and could be even out of scope afterwards.

File: drivers/nutdrv_qx.c (hunk 3 above)
Comment (blaa) [reply drivers/nutdrv_qx.c:1869]: Fixed; I tried %z even before but that didn't really work.

File: drivers/nutdrv_qx.c (hunk 1 above)
Comment (jimklimov) [reply drivers/nutdrv_qx.c:1859]: Well, `ret` should say how much info was actually returned by the libusb call; if it is less than the expected READ_SIZE - the rest of `tmpbuf[]` is garbage. If it is more... oops :)

Comment (blaa) [reply drivers/nutdrv_qx.c:1859]: Yes, but that is checked immediately after the read in the "context" of reading USB. I'm not fluent in libusb API though and I'm unsure how it might fail. It should not read MORE data though than passed buffer or there's really a problem.

I just assume after the read+check that the tmpbuf has data read. The data can be garbage because of other fun reasons though. This USB read could be even extracted to separate function probably (with ret being available only within)

I just added a check for turned off UPS... my current one is in this state. The USB returns 0x00 bytes in this case, but DOES return data. Never tried that before.

File: drivers/nutdrv_qx.c [hunk 4]
```diff
@@ -1813,18 +1814,21 @@ static int	armac_command(const char *cmd, char *buf, size_t buflen)
...
 		ret = usb_interrupt_read(udev,
 			0x81,
-			(usb_ctrl_charbuf)tmpbuf, 6, 1000);
+			(usb_ctrl_charbuf)tmpbuf, READ_SIZE, 1000);
 
 		/* Any errors here mean that we are unable to read a reply
 		 * (which will happen after successfully writing a command
 		 * to the UPS) */
-		if (ret != 6) {
+		if (ret != READ_SIZE) {
```
Comment (jimklimov) [inline drivers/nutdrv_qx.c:1828]: Ugh,

````
comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   if (ret != READ_SIZE) {
````

need to cast (probably `(int)READ_SIZE` to become signed in this case).

Comment (blaa) [reply drivers/nutdrv_qx.c:1828]: I should have remote access to my UPS tomorrow. I'll try to check it then.

Comment (jimklimov) [reply drivers/nutdrv_qx.c:1828]: Sounds great, thanks for the update!

Comment (blaa) [reply drivers/nutdrv_qx.c:1840]: I've finally changed READ_SIZE to int, because the argument in `usb_read_interrupt` is int as well.

My family. Well - that was funny. My sister enabled the UPS, but it was ON BATTERY. So I had a limited time window before it discharged to test the changes. It made me make some changes though. Original code didn't work well (ended reading on \r, then some additional messages were left in buffer and next commands failed).

I added a buffer cleanup at the beginning which seem to work nice and handle more cases. That made it work pretty stable on my UPS as far as I can tell after the tests.

**Comment by blaa** [comment]
Trace -DDDD from a new UPS: https://pastebin.com/2dgc2X0Z
(the debug ASCII output is a bit changed but that is not in PR as it was work in progress)

Debug output from my UPS (older?) works as well:
```
112.966856     [D4] armac command Q1                                                                                                                                                          
 112.968197     [D4] armac cleanup ret i=0 ret=6 ctrl=c0                                                                                                                                       
.0<3.091193     [D4] read: ret 6 buf 81: 28 30 0d 2e 30  >(0                                                                                                                                   
.0<3.103211     [D4] read: ret 6 buf c1: 30 30 0d 2e 30  >00                                                                                                                                   
.0<3.115180     [D4] read: ret 6 buf 82: 30 30 0d 2e 30  >00                                                                                                                                   
 113.117144     [D4] read: ret 6 buf c3: 2e 30 20 2e 30  >.0 .0<                                                                                                                               
 113.120150     [D4] read: ret 6 buf 81: 31 30 20 2e 30  >10 .0<                                                                                                                               
 113.132178     [D4] read: ret 6 buf c1: 34 30 20 2e 30  >40 .0<                                                                                                                               
 113.144159     [D4] read: ret 6 buf 82: 30 2e 20 2e 30  >0. .0<                                                                                                                               
 113.146149     [D4] read: ret 6 buf c3: 30 20 32 2e 30  >0 2.0<                                                                                                                               
 113.149173     [D4] read: ret 6 buf 81: 32 20 32 2e 30  >2 2.0<                                                                                                                               
 113.161167     [D4] read: ret 6 buf c1: 37 20 32 2e 30  >7 2.0<                                                                                                                               
 113.173159     [D4] read: ret 6 buf 82: 2e 30 32 2e 30  >.02.0<                                                                                                                               
 113.175157     [D4] read: ret 6 buf c3: 20 30 30 2e 30  > 00.0<                                                                                                                               
 113.178158     [D4] read: ret 6 buf 81: 32 30 30 2e 30  >200.0<                                                                                                                               
 113.190157     [D4] read: ret 6 buf c1: 20 30 30 2e 30  > 00.0<                                                                                                                               
 113.202161     [D4] read: ret 6 buf 82: 30 30 30 2e 30  >000.0<                                                                                                                               
 113.204154     [D4] read: ret 6 buf c3: 2e 30 20 2e 30  >.0 .0<                                                                                                                               
 113.207150     [D4] read: ret 6 buf 81: 34 30 20 2e 30  >40 .0<                                                                                                                               
 113.219174     [D4] read: ret 6 buf c1: 36 30 20 2e 30  >60 .0<                                                                                                                               
 113.231165     [D4] read: ret 6 buf 82: 2e 38 20 2e 30  >.8 .0<                                                                                                                               
 113.233157     [D4] read: ret 6 buf c3: 20 35 36 2e 30  > 56.0<                                                                                                                               
 113.237149     [D4] read: ret 6 buf 81: 2e 35 36 2e 30  >.56.0<                                                                                                                               
 113.249168     [D4] read: ret 6 buf c1: 30 35 36 2e 30  >056.0<                                                                                                                               
 113.261155     [D4] read: ret 6 buf 83: 20 31 30 2e 30  > 10.0<                                                                                                                               
 113.263151     [D4] read: ret 6 buf c2: 30 30 30 2e 30  >000.0<                                                                                                                               
 113.266152     [D4] read: ret 6 buf 81: 31 30 30 2e 30  >100.0<                                                                                                                               
 113.278161     [D4] read: ret 6 buf c1: 30 30 30 2e 30  >000.0<                                                                                                                               
 113.290155     [D4] read: ret 6 buf 82: 30 30 30 2e 30  >000.0<                                                                                                                               
00.0<292159     [D4] read: ret 6 buf c1: 0d 30 30 2e 30  >                                                                                                                                     
 113.292169     [D3] armac command Q1 response read: '(000.0 140.0 227.0 002 00.0 46.8 56.0 10001000'                          
```

So - after the current changes both known versions seems to work ok as far as I can tell now.

File: drivers/nutdrv_qx.c [hunk 5]
```diff
@@ -1788,6 +1789,17 @@ static int	armac_command(const char *cmd, char *buf, size_t buflen)
...
 
+	/* Cleanup buffer before sending a new command */
+	for (i = 0; i < 10; i++) {
+		ret = usb_interrupt_read(udev, 0x81,
+			(usb_ctrl_charbuf)tmpbuf, READ_SIZE, 100);
+		if (ret != READ_SIZE) {
+			// Timeout - buffer is clean.
+			break;
+		}
+		upsdebugx(4, "armac cleanup ret i=%ld ret=%d ctrl=%02hhx", i, ret, tmpbuf[0]);
```
Comment (jimklimov) [inline drivers/nutdrv_qx.c:1800]:
```suggestion
		upsdebugx(4, "armac cleanup ret i=%" PRIuSIZE " ret=%d ctrl=%02hhx", i, ret, tmpbuf[0]);
```

**Comment by jimklimov** [comment]
CC @bdkacz @desertwitch @convicte : Cheers, would any of you guys please be able to build and test https://github.com/blaa/nut/tree/master to see if it supports all of your armac-talking devices?

File: drivers/nutdrv_qx.c
Comment (blaa) [inline drivers/nutdrv_qx.c:1]: Hm... TBH, bytes_available could be an `int` as well. Having unsigned type here seem to be more problems than it's worth.

BTW, I don't seem to see compilation warnings related to this. Maybe something I change locally. Or different compiler? Or are you using a linter?

**Comment by blaa** [comment]
> CC @bdkacz @desertwitch @convicte : Cheers, would any of you guys please be able to build and test https://github.com/blaa/nut/tree/master to see if it supports all of your armac-talking devices?

I've tested this code with @convicte already. He seems to be staying with Armac so we can do a final test after merge (maybe after release, unsure when it's planned).

I can do more tests with mine UPS after 21 of August. Feel free to freeze this change until that time. 

bdkacz didn't respond earlier so I guess we can't really hope for him to test that. ;)

File: drivers/nutdrv_qx.c
Comment (jimklimov) [reply drivers/nutdrv_qx.c:1]: It's all on the NUT CI farm running several generations of GCC and CLANG across several OSes, you can see links from the icon near commit hash above. Some lead to Jenkins at e.g. https://ci.networkupstools.org/job/nut/job/nut/job/PR-2005/6/ and the page has artifacts for failed scenarios. Occasionally faults are due to networking, storage, etc. circumstances of the farm; usually due to some such linting infraction in the too-new or too-old toolkit. We aim to pass green everywhere so "real" bugs can be noticed by a surprising non-green result :)

**Comment by jimklimov** [comment]
In the last round, something new:
````
nutdrv_qx.c:1765:14: error: variable length array folded to constant array as an extension [-Werror,-Wgnu-folding-constant]
        char tmpbuf[READ_SIZE];
````

I guess it should after all portably be a macro like `LARGEBUF` and `SMALLBUF` elsewhere. For that matter, one named for the use-case, e.g. `#define ARMAC_READ_SIZE 6` :\

**Comment by desertwitch** [comment]
Interesting, I've built this without any warnings or errors on Slackware v15 for @convicte to test on his UNRAID installation (don't have an Armac UPS myself). Waiting to hear back from him.

**Comment by jimklimov** [comment]
Yeah, the other 138 build matrix combos were also fine with this, just a couple squealed ;)

**Comment by blaa** [comment]
I have one more person with some weird new configuration (Vultech). I'll try to support it via this latest commit but will have to make some tests with him. It's probably better to wait a bit and make him work as well.

**Comment by mibofra** [comment]
Hi all! @blaa I have wanted to check if there was any progress on https://github.com/networkupstools/nut/issues/640 , and well, even if with some delay, I am still alive :D .

While I've to check https://github.com/networkupstools/nut/issues/640 if supports really my ups (I have to compile nutdrv_qx for openwrt, where the ups is attached), I have noticed youre last comment here.

Well, my ups is specifically a Vultech, an UPS1000VA-PURE/UPS1500VA-PURE https://www.vultech.it/it/gruppi-di-continuita/915-ups-1500va-pure-line-interactive-onda-sinusoidale-pura-gruppo-di-continuit%C3%A0-8052780300902.html

So, at this point, I will wait for another commit :D , and ping me if you need something for that configuration too.

**Comment by blaa** [comment]
@mibofra you can help by pasting nutdrv_qx output with subdriver armac and "-DDDD" debugging level. It's great time to push it a bit forward as I'm still on vacation and can do some night-time hacking. I'm far from my UPS though.

Something like this: `./nutdrv_qx -a armac -u root -DDDD -x productid=1234 -x vendorid=0925 -x subdriver=armac`

With each new trace our understanding of how this transmission works improves.

**Comment by blaa** [comment]
We've got an "almost" elegant solution by treating NULL bytes within the status bits as zeroes on Vultech V2000. This makes the UPS answer with another 6 bytes and eventually we reach \r byte and number of status bits matches the requirements of Qx / Megatec protocol.

It might've worked previously because there was no 0x00 detection and null byte was just included within the output. Still, it worked by accident AFAIK.

```
419.987514     [D4] armac command Q1
 419.988307     [D4] armac cleanup ret i=0 ret=6 ctrl=c0
 420.119402     [D4] read: ret 6 buf 81: 28 30 31 30 30  >(0100<
 420.130383     [D4] read: ret 6 buf c1: 32 30 31 30 30  >20100<
 420.141408     [D4] read: ret 6 buf 82: 33 33 31 30 30  >33100<
 420.152201     [D4] read: ret 6 buf c3: 2e 30 20 30 30  >.0 00<
 420.153237     [D4] read: ret 6 buf 82: 30 30 20 30 30  >00 00<
 420.164299     [D4] read: ret 6 buf c1: 30 30 20 30 30  >00 00<
 420.175293     [D4] read: ret 6 buf 82: 2e 30 20 30 30  >.0 00<
 420.186358     [D4] read: ret 6 buf c3: 20 32 33 30 30  > 2300<
 420.190322     [D4] read: ret 6 buf 83: 33 2e 30 30 30  >3.000<
 420.194323     [D4] read: ret 6 buf c1: 20 2e 30 30 30  > .000<
 420.205358     [D4] read: ret 6 buf 81: 30 2e 30 30 30  >0.000<
 420.216318     [D4] read: ret 6 buf c2: 31 34 30 30 30  >14000<
 420.227445     [D4] read: ret 6 buf 83: 20 34 39 30 30  > 4900<
 420.228334     [D4] read: ret 6 buf c2: 2e 30 39 30 30  >.0900<
 420.239461     [D4] read: ret 6 buf 81: 20 30 39 30 30  > 0900<
 420.250411     [D4] read: ret 6 buf c2: 32 37 39 30 30  >27900<
 420.261405     [D4] read: ret 6 buf 83: 2e 30 20 30 30  >.0 00<
 420.265468     [D4] read: ret 6 buf c3: 32 30 2e 30 30  >20.00<
 420.269465     [D4] read: ret 6 buf 81: 38 30 2e 30 30  >80.00<
 420.280322     [D4] read: ret 6 buf c1: 20 30 2e 30 30  > 0.00<
 420.291469     [D4] read: ret 6 buf 82: 30 30 2e 30 30  >00.00<
 420.302465     [D4] read: ret 6 buf c3: 30 30 31 30 30  >00100<
 420.303511     [D4] read: ret 6 buf 82: 00 30 31 30 30  >             <- This has 0x00 and '0', will be read as "00"
 420.303515     [D3] found null byte in status bits at 43 byte, assuming 0.
 420.314425     [D4] read: ret 6 buf c1: 31 30 31 30 30  >10100<    <- this has '1'
0100<325432     [D4] read: ret 6 buf 81: 0d 30 31 30 30  >              <- and this finishes with \r.
 420.325442     [D3] armac command Q1 response read: '(233.0 000.0 233.0 014 49.0 27.0 20.8 00001001'
```

I'll publish code changes later.

Maybe adding a doc file with all possible transfers for this drivers makes some sense. I've even coded a testcase where I emulate USB locally, but it's just a hack on the driver that requires USB device to connect to SOMETHING. My knowledge here is too weak to create a proper automatic test.

**Comment by jimklimov** [comment]
Sounds great, thanks!

**Comment by jimklimov** [comment]
Thanks again! Posted some comments about the wording and markup of the new text file, but maybe posted that to commit and not PR :) see: https://github.com/networkupstools/nut/commit/4b105f81c1ed2f17b49b1c36ab4ae1ba0065b713

**Comment by jimklimov** [comment]
Also, it may be worth listing the devices in `NEWS`as examples of what was not supported before and is now. Updating `docs/nut.dict` if needed (Makefile will yell how if `make spellcheck` fails).

**Comment by blaa** [comment]
Not much new ideas.  After 21.08 I should have access to my UPS and can conduct some more testing then.
I have a local patch/changes that creates an Frankenstein-type testcase for data. Hard to merge it though.

@mibofra could try this with his UPS for some additional testdata.

As for the docs - unsure. TBH, whatever you think is fine. It would be cool if you could move it though if you want it there. ;) I've never taken a look at this other repo so the findability might not be that great (I usually vote for monorepos).

**Comment by jimklimov** [comment]
Oh, well. For this one the point is a bit moot - found there is a `nutdrv_qx-subdrivers.txt` which already mixes development and protocol details, so adding your file to the generated document chain (or just merging it into the existing file) makes sense too.

The nut-website ones are more about formal and exhaustive protocol definitions, whether from vendors or reverse-engineering...

**Comment by blaa** [comment]
If you prefer I can merge this new file with nutdrv_qx-subdrivers.txt as a subsection maybe?

**Comment by jimklimov** [comment]
Thinking of it - yes, please. It would be easier than linking to it from other docs and makefiles and missing half. :) And would be easier to find for those who'd need it, too :)

**Comment by jimklimov** [comment]
Thanks for the improvements and for the patience! :)

**Comment by jimklimov** [comment]
For next times, keep in mind it would be more sustainable for you to start a PR from some feature branch, not master. Especially when it is predictable that it won't be a five-minute merge win :)

**Comment by blaa** [comment]
I'm glad we'd opportunity to improve this driver. Now lets see what new bugs or UPSes appear. ;)

I'm more used to a Bitbucket PR model (we have it at work). I'll have to look up how it usually works on github. For me the small problem is using two repositories (two remotes because of a fork), so I assume you mean a feature branch on the nut repository - if that's possible then certainly would be easier.

Cheers and thanks for your work here. ;)

What would change a feature branch though? It's still on my repo right?

**Comment by blaa** [comment]
It works on my UPS still ok - finally tested it.

**Comment by jimklimov** [comment]
Thanks for the contribution, and time, and diligence :)

PS: If you have a chance to chime in, issue 1987 was last waiting for suggestions about contributing a (probably) `nutdrv_qx` subdriver -- the SMS Brazil devices seem to use some sort of binarized Qx protocol, if such description makes sense :) So if possible, it better get wedged into the common framework, with standalone driver being last resort. My theoretical understanding only goes so far, help from experienced veterans fresh from the trenches would be very welcome :)

**Comment by blaa** [comment]
Indeed from the log - it looks like it's working just fine. So for future reference that was Vultech UPS1000VA-PURE/UPS1500VA-PURE UPS.  In case of problems - drop us a note. Scheduling a test for example should work too. Changing beeper setting - maybe not.
