### PR TITLE
Cast to unsigned type when interpreting HID descriptor length bytes (libusb 0.1)

### LINKED ISSUE #1261: APC Smart-UPS X 750 - some data is missing
Hello,

```
battery.charge: 66
battery.charge.low: 10
battery.charge.warning: 50
battery.runtime: 65535
battery.runtime.low: 150
battery.type: PbAc
battery.voltage: 52.0
battery.voltage.nominal: 48.0
device.mfr: American Power Conversion 
device.model: Smart-UPS X 750 
device.serial: <serial>
device.type: ups
driver.name: usbhid-ups
driver.parameter.pollfreq: 30
driver.parameter.pollinterval: 2
driver.parameter.port: auto
driver.parameter.synchronous: no
driver.version: 2.7.4
driver.version.data: APC HID 0.96
driver.version.internal: 0.41
ups.beeper.status: enabled
ups.delay.shutdown: 20
ups.firmware: COM 03.8 / UPS 03.8
ups.mfr: American Power Conversion 
ups.mfr.date: 2011/11/28
ups.model: Smart-UPS X 750 
ups.productid: 0003
ups.serial:  <serial>
ups.status: OL CHRG
ups.timer.reboot: -1
ups.timer.shutdown: -1
ups.vendorid: 051d
```

Device connected via USB. It is lacking some data like ups load, input/output voltages and so on (visible on older Smart-UPS 1000 RM that I'm replacing).

I found some topics suggesting that it may use modbus, not sure if that's the case here (at least manual don't mention it, nor it is mentioned in menus). Any suggestions?

Below is the descriptor data:

```
Bus 002 Device 006: ID 051d:0003 American Power Conversion UPS
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x051d American Power Conversion
  idProduct          0x0003 UPS
  bcdDevice            1.06
  iManufacturer           1 American Power Conversion 
  iProduct                2 Smart-UPS X 750  FW:COM 03.8 / UPS 03.8
  iSerial                 3 <serial>
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0029
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x60
      (Missing must-be-set bit!)
      Self Powered
      Remote Wakeup
    MaxPower                2mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.00
          bCountryCode           33 US
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     425
          Report Descriptor: (length is 425)
            Item(Global): Usage Page, data= [ 0x84 ] 132
                            Power Device Page
            Item(Local ): Usage, data= [ 0x04 ] 4
                            UPS
            Item(Main  ): Collection, data= [ 0x01 ] 1
                            Application
            Item(Local ): Usage, data= [ 0x24 ] 36
                            Power Summary
            Item(Main  ): Collection, data= [ 0x02 ] 2
                            Logical
            Item(Global): Report ID, data= [ 0x01 ] 1
            Item(Local ): Usage, data= [ 0xfe ] 254
                            iProduct
            Item(Local ): String Index, data= [ 0x02 ] 2
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x01 ] 1
            Item(Global): Logical Minimum, data= [ 0x00 ] 0
            Item(Global): Logical Maximum, data= [ 0xff 0x00 ] 255
            Item(Main  ): Feature, data= [ 0x22 ] 34
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Global): Report ID, data= [ 0x02 ] 2
            Item(Local ): Usage, data= [ 0xff ] 255
                            iSerialNumber
            Item(Local ): String Index, data= [ 0x03 ] 3
            Item(Main  ): Feature, data= [ 0x22 ] 34
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Global): Report ID, data= [ 0x03 ] 3
            Item(Local ): Usage, data= [ 0xfd ] 253
                            iManufacturer
            Item(Local ): String Index, data= [ 0x01 ] 1
            Item(Main  ): Feature, data= [ 0x22 ] 34
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Global): Usage Page, data= [ 0x85 ] 133
                            Battery System Page
            Item(Global): Report ID, data= [ 0x04 ] 4
            Item(Local ): Usage, data= [ 0x8f ] 143
                            iOEMInformation
            Item(Local ): String Index, data= [ 0x01 ] 1
            Item(Main  ): Feature, data= [ 0x22 ] 34
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Global): Report ID, data= [ 0x05 ] 5
            Item(Local ): Usage, data= [ 0x89 ] 137
                            iDeviceChemistry
            Item(Local ): String Index, data= [ 0x04 ] 4
            Item(Main  ): Feature, data= [ 0x22 ] 34
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Global): Report ID, data= [ 0x06 ] 6
            Item(Local ): Usage, data= [ 0x8b ] 139
                            Rechargeable
            Item(Main  ): Feature, data= [ 0x22 ] 34
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Local ): Usage, data= [ 0x2c ] 44
                            Capacity Mode
            Item(Main  ): Feature, data= [ 0x22 ] 34
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Global): Report ID, data= [ 0x0e ] 14
            Item(Local ): Usage, data= [ 0x83 ] 131
                            Design Capacity
            Item(Global): Logical Maximum, data= [ 0x64 ] 100
            Item(Main  ): Feature, data= [ 0x22 ] 34
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Local ): Usage, data= [ 0x67 ] 103
                            Full Charge Capacity
            Item(Main  ): Feature, data= [ 0x22 ] 34
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Global): Report ID, data= [ 0x0c ] 12
            Item(Local ): Usage, data= [ 0x66 ] 102
                            Remaining Capacity
            Item(Main  ): Input, data= [ 0x22 ] 34
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Local ): Usage, data= [ 0x66 ] 102
                            Remaining Capacity
            Item(Main  ): Feature, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Report ID, data= [ 0x10 ] 16
            Item(Local ): Usage, data= [ 0x8d ] 141
                            Capacity Granularity 1
            Item(Main  ): Feature, data= [ 0x22 ] 34
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Local ): Usage, data= [ 0x8e ] 142
                            Capacity Granularity 2
            Item(Main  ): Feature, data= [ 0x22 ] 34
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Global): Report ID, data= [ 0x0f ] 15
            Item(Local ): Usage, data= [ 0x8c ] 140
                            Warning Capacity Limit
            Item(Main  ): Feature, data= [ 0x22 ] 34
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Global): Report ID, data= [ 0x11 ] 17
            Item(Local ): Usage, data= [ 0x29 ] 41
                            Remaining Capacity Limit
            Item(Main  ): Feature, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Report ID, data= [ 0x09 ] 9
            Item(Local ): Usage, data= [ 0x85 ] 133
                            Manufacturer Date
            Item(Global): Report Size, data= [ 0x10 ] 16
            Item(Global): Logical Maximum, data= [ 0xff 0xff 0x00 0x00 ] 65535
            Item(Main  ): Feature, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Report ID, data= [ 0x0d ] 13
            Item(Local ): Usage, data= [ 0x68 ] 104
                            Run Time To Empty
            Item(Global): Logical Maximum, data= [ 0xff 0xff 0x00 0x00 ] 65535
            Item(Global): Unit, data= [ 0x01 0x10 ] 4097
                            System: SI Linear, Unit: Seconds
            Item(Global): Unit Exponent, data= [ 0x00 ] 0
                            Unit Exponent: 0
            Item(Main  ): Input, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Local ): Usage, data= [ 0x68 ] 104
                            Run Time To Empty
            Item(Main  ): Feature, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Usage Page, data= [ 0x84 ] 132
                            Power Device Page
            Item(Global): Report ID, data= [ 0x12 ] 18
            Item(Local ): Usage, data= [ 0x57 ] 87
                            Delay Before Shutdown
            Item(Global): Logical Minimum, data= [ 0xff 0xff ] 65535
            Item(Global): Logical Maximum, data= [ 0xff 0x7f ] 32767
            Item(Main  ): Feature, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Report ID, data= [ 0x13 ] 19
            Item(Local ): Usage, data= [ 0x55 ] 85
                            Delay Before Reboot
            Item(Global): Report Size, data= [ 0x18 ] 24
            Item(Global): Logical Minimum, data= [ 0xff 0xff 0xff 0xff ] -1
            Item(Global): Logical Maximum, data= [ 0x18 0xc5 0x13 0x00 ] 1295640
            Item(Main  ): Feature, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Usage Page, data= [ 0x85 ] 133
                            Battery System Page
            Item(Global): Report ID, data= [ 0x08 ] 8
            Item(Local ): Usage, data= [ 0x2a ] 42
                            Remaining Time Limit
            Item(Global): Logical Maximum, data= [ 0x64 0x05 0x00 0x00 ] 1380
            Item(Global): Logical Minimum, data= [ 0x78 0x00 ] 120
            Item(Main  ): Input, data= [ 0x22 ] 34
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Local ): Usage, data= [ 0x2a ] 42
                            Remaining Time Limit
            Item(Main  ): Feature, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Usage Page, data= [ 0x84 ] 132
                            Power Device Page
            Item(Global): Report ID, data= [ 0x0a ] 10
            Item(Local ): Usage, data= [ 0x40 ] 64
                            Config Voltage
            Item(Global): Report Size, data= [ 0x10 ] 16
            Item(Global): Logical Minimum, data= [ 0x00 ] 0
            Item(Global): Logical Maximum, data= [ 0xff 0xff 0x00 0x00 ] 65535
            Item(Global): Unit, data= [ 0x21 0xd1 0xf0 0x00 ] 15782177
                            System: SI Linear, Unit: Centimeter^2*Gram*Seconds^-3*Ampere^-1
            Item(Global): Unit Exponent, data= [ 0x05 ] 5
                            Unit Exponent: 5
            Item(Main  ): Feature, data= [ 0x22 ] 34
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Global): Report ID, data= [ 0x0b ] 11
            Item(Local ): Usage, data= [ 0x30 ] 48
                            Voltage
            Item(Main  ): Feature, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Report ID, data= [ 0x14 ] 20
            Item(Local ): Usage, data= [ 0x5a ] 90
                            Audible Alarm Control
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Logical Minimum, data= [ 0x01 ] 1
            Item(Global): Logical Maximum, data= [ 0x03 ] 3
            Item(Global): Unit, data= [ 0x00 ] 0
                            System: None, Unit: (None)
            Item(Global): Unit Exponent, data= [ 0x00 ] 0
                            Unit Exponent: 0
            Item(Main  ): Input, data= [ 0x22 ] 34
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Local ): Usage, data= [ 0x5a ] 90
                            Audible Alarm Control
            Item(Main  ): Feature, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Local ): Usage, data= [ 0x02 ] 2
                            Present Status
            Item(Main  ): Collection, data= [ 0x02 ] 2
                            Logical
            Item(Global): Report ID, data= [ 0x07 ] 7
            Item(Global): Usage Page, data= [ 0x85 ] 133
                            Battery System Page
            Item(Local ): Usage, data= [ 0x44 ] 68
                            Charging
            Item(Global): Report Size, data= [ 0x01 ] 1
            Item(Global): Logical Minimum, data= [ 0x00 ] 0
            Item(Global): Logical Maximum, data= [ 0x01 ] 1
            Item(Main  ): Input, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Local ): Usage, data= [ 0x44 ] 68
                            Charging
            Item(Main  ): Feature, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Local ): Usage, data= [ 0x45 ] 69
                            Discharging
            Item(Main  ): Input, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Local ): Usage, data= [ 0x45 ] 69
                            Discharging
            Item(Main  ): Feature, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Local ): Usage, data= [ 0xd0 ] 208
                            AC Present
            Item(Main  ): Input, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Local ): Usage, data= [ 0xd0 ] 208
                            AC Present
            Item(Main  ): Feature, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Local ): Usage, data= [ 0xd1 ] 209
                            Battery Present
            Item(Main  ): Input, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Local ): Usage, data= [ 0xd1 ] 209
                            Battery Present
            Item(Main  ): Feature, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Local ): Usage, data= [ 0x42 ] 66
                            Below Remaining Capacity Limit
            Item(Main  ): Input, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Local ): Usage, data= [ 0x42 ] 66
                            Below Remaining Capacity Limit
            Item(Main  ): Feature, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Usage Page, data= [ 0x84 ] 132
                            Power Device Page
            Item(Local ): Usage, data= [ 0x68 ] 104
                            Shutdown Requested
            Item(Main  ): Input, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Local ): Usage, data= [ 0x68 ] 104
                            Shutdown Requested
            Item(Main  ): Feature, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Local ): Usage, data= [ 0x69 ] 105
                            Shutdown  Imminent
            Item(Main  ): Input, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Local ): Usage, data= [ 0x69 ] 105
                            Shutdown  Imminent
            Item(Main  ): Feature, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Usage Page, data= [ 0x85 ] 133
                            Battery System Page
            Item(Local ): Usage, data= [ 0x43 ] 67
                            Remaining Time Limit Expired
            Item(Main  ): Input, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Local ): Usage, data= [ 0x43 ] 67
                            Remaining Time Limit Expired
            Item(Main  ): Feature, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Usage Page, data= [ 0x84 ] 132
                            Power Device Page
            Item(Local ): Usage, data= [ 0x73 ] 115
                            Communication Lost
            Item(Main  ): Input, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Local ): Usage, data= [ 0x73 ] 115
                            Communication Lost
            Item(Main  ): Feature, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Usage Page, data= [ 0x85 ] 133
                            Battery System Page
            Item(Local ): Usage, data= [ 0x4b ] 75
                            Need Replacement
            Item(Main  ): Input, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Local ): Usage, data= [ 0x4b ] 75
                            Need Replacement
            Item(Main  ): Feature, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Usage Page, data= [ 0x84 ] 132
                            Power Device Page
            Item(Local ): Usage, data= [ 0x65 ] 101
                            Overload
            Item(Main  ): Input, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Local ): Usage, data= [ 0x65 ] 101
                            Overload
            Item(Main  ): Feature, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Usage Page, data= [ 0x85 ] 133
                            Battery System Page
            Item(Local ): Usage, data= [ 0xdb ] 219
                            Voltage Not Regulated
            Item(Main  ): Input, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Local ): Usage, data= [ 0xdb ] 219
                            Voltage Not Regulated
            Item(Main  ): Feature, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Usage Page, data= [ 0x86 0xff ] 65414
                            (null)
            Item(Local ): Usage, data= [ 0x80 ] 128
                            (null)
            Item(Main  ): Input, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Local ): Usage, data= [ 0x80 ] 128
                            (null)
            Item(Main  ): Feature, data= [ 0xa2 ] 162
                            Data Variable Absolute No_Wrap Linear
                            No_Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Report Count, data= [ 0x03 ] 3
            Item(Main  ): Input, data= [ 0x01 ] 1
                            Constant Array Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Main  ): Feature, data= [ 0x01 ] 1
                            Constant Array Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Main  ): End Collection, data=none
            Item(Main  ): End Collection, data=none
            Item(Global): Usage Page, data= [ 0x86 0xff ] 65414
                            (null)
            Item(Global): Report ID, data= [ 0x89 ] 137
            Item(Local ): Usage, data= [ 0xfd ] 253
                            (null)
            Item(Global): Logical Minimum, data= [ 0x00 ] 0
            Item(Global): Logical Maximum, data= [ 0xff 0x00 ] 255
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x3f ] 63
            Item(Main  ): Input, data= [ 0x02 ] 2
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Global): Report ID, data= [ 0x90 ] 144
            Item(Local ): Usage, data= [ 0xfc ] 252
                            (null)
            Item(Global): Logical Minimum, data= [ 0x00 ] 0
            Item(Global): Logical Maximum, data= [ 0xff 0x00 ] 255
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x3f ] 63
            Item(Main  ): Output, data= [ 0x02 ] 2
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Main  ): End Collection, data=none
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval              10
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval              10
can't get device qualifier: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
Device Status:     0x0002
  (Bus Powered)
  Remote Wakeup Enabled
```

### LINKED ISSUE #1312: Salicru Twin Pro 2
Hi

Did someone get this UPS to work?, I have tried the debian package with apt and also installing from binaries but no luck:

I have this UPS installed in a Proxmox machine so I don't know if this is related. Here are some info I gathered:

```
root@PROXMOX:/usr/local/ups/bin# ./nut-scanner
Scanning USB bus.
No start IP, skipping NUT bus (old connect method)
[nutdev1]
        driver = "usbhid-ups"
        port = "auto"
        vendorid = "2E66"
        productid = "0201"
        product = "SLC TWIN PRO2<=3KVA"
        serial = "232019D70264"
        vendor = "Salicru"
        bus = "002"
```

```
root@PROXMOX:/usr/local/ups/bin# ./usbhid-ups -DD -a salicru -u root
Network UPS Tools - Generic HID driver 0.45 (2.7.4-4698-g381a81fc)
USB communication driver (libusb 0.1) 0.42
   0.000000     [D1] Built-in default or configured user for drivers 'nut' was ignored due to 'root' specified on command line
   0.000017     [D1] debug level is '2'
   0.001716     [D2] Initializing an USB-connected UPS with library libusb-0.1 (or compat) (NUT subdriver name='USB communication driver (libusb 0.1)' ver='0.42')
   0.001732     [D1] upsdrv_initups (non-SHUT)...
   0.139629     [D2] Checking device (8087/8002) (003/002)
   0.207815     [D2] - VendorID: 8087
   0.207844     [D2] - ProductID: 8002
   0.207847     [D2] - Manufacturer: unknown
   0.207850     [D2] - Product: unknown
   0.207856     [D2] - Serial Number: unknown
   0.207887     [D2] - Bus: 003
   0.207894     [D2] - Device: 002
   0.207902     [D2] - Device release number: 0005
   0.207911     [D2] Trying to match device
   0.207919     [D2] match_function_subdriver (non-SHUT mode): matching a device...
   0.207932     [D2] match_function_subdriver (non-SHUT mode): failed to match a subdriver to vendor and/or product ID
   0.207940     [D2] Device does not match - skipping
   0.207963     [D2] Checking device (1D6B/0002) (003/001)
   0.208072     [D2] - VendorID: 1d6b
   0.208084     [D2] - ProductID: 0002
   0.208098     [D2] - Manufacturer: Linux 5.4.162-1-pve ehci_hcd
   0.208105     [D2] - Product: EHCI Host Controller
   0.208113     [D2] - Serial Number: 0000:00:1d.0
   0.208120     [D2] - Bus: 003
   0.208127     [D2] - Device: 001
   0.208135     [D2] - Device release number: 0504
   0.208142     [D2] Trying to match device
   0.208149     [D2] match_function_subdriver (non-SHUT mode): matching a device...
   0.208159     [D2] match_function_subdriver (non-SHUT mode): failed to match a subdriver to vendor and/or product ID
   0.208166     [D2] Device does not match - skipping
   0.208179     [D2] Checking device (1D6B/0003) (004/001)
   0.208372     [D2] - VendorID: 1d6b
   0.208383     [D2] - ProductID: 0003
   0.208388     [D2] - Manufacturer: Linux 5.4.162-1-pve xhci-hcd
   0.208395     [D2] - Product: xHCI Host Controller
   0.208402     [D2] - Serial Number: 0000:00:14.0
   0.208405     [D2] - Bus: 004
   0.208408     [D2] - Device: 001
   0.208413     [D2] - Device release number: 0504
   0.208418     [D2] Trying to match device
   0.208423     [D2] match_function_subdriver (non-SHUT mode): matching a device...
   0.208432     [D2] match_function_subdriver (non-SHUT mode): failed to match a subdriver to vendor and/or product ID
   0.208437     [D2] Device does not match - skipping
   0.208538     [D2] Checking device (2E66/0201) (002/010)
   0.210053     [D2] - VendorID: 2e66
   0.210064     [D2] - ProductID: 0201
   0.210071     [D2] - Manufacturer: Salicru
   0.210078     [D2] - Product: SLC TWIN PRO2<=3KVA
   0.210084     [D2] - Serial Number: 232019D70264
   0.210091     [D2] - Bus: 002
   0.210097     [D2] - Device: 010
   0.210104     [D2] - Device release number: 0129
   0.210110     [D2] Trying to match device
   0.210116     [D2] match_function_subdriver (non-SHUT mode): matching a device...
   0.210218     [D2] Device matches
   0.210381     [D2] Warning: HID descriptor, method 1 failed
   0.210390     [D2] Warning: HID descriptor, method 2 failed
   0.210396     [D2] Unable to retrieve any HID descriptor
   0.210415     [D2] Checking device (0E6A/02C0) (002/003)
   0.214274     [D2] - VendorID: 0e6a
   0.214289     [D2] - ProductID: 02c0
   0.214294     [D2] - Manufacturer: dakai
   0.214300     [D2] - Product: PS/2+USB Keyboard
   0.214304     [D2] - Serial Number: unknown
   0.214309     [D2] - Bus: 002
   0.214316     [D2] - Device: 003
   0.214321     [D2] - Device release number: 4e01
   0.214325     [D2] Trying to match device
   0.214328     [D2] match_function_subdriver (non-SHUT mode): matching a device...
   0.214339     [D2] match_function_subdriver (non-SHUT mode): failed to match a subdriver to vendor and/or product ID
   0.214346     [D2] Device does not match - skipping
   0.214358     [D2] Checking device (046D/C05A) (002/002)
   0.216372     [D2] - VendorID: 046d
   0.216380     [D2] - ProductID: c05a
   0.216388     [D2] - Manufacturer: Logitech
   0.216394     [D2] - Product: USB Optical Mouse
   0.216399     [D2] - Serial Number: unknown
   0.216406     [D2] - Bus: 002
   0.216413     [D2] - Device: 002
   0.216419     [D2] - Device release number: 6300
   0.216426     [D2] Trying to match device
   0.216437     [D2] match_function_subdriver (non-SHUT mode): matching a device...
   0.216448     [D2] match_function_subdriver (non-SHUT mode): failed to match a subdriver to vendor and/or product ID
   0.216456     [D2] Device does not match - skipping
   0.216468     [D2] Checking device (1D6B/0002) (002/001)
   0.216565     [D2] - VendorID: 1d6b
   0.216575     [D2] - ProductID: 0002
   0.216581     [D2] - Manufacturer: Linux 5.4.162-1-pve xhci-hcd
   0.216586     [D2] - Product: xHCI Host Controller
   0.216590     [D2] - Serial Number: 0000:00:14.0
   0.216595     [D2] - Bus: 002
   0.216600     [D2] - Device: 001
   0.216606     [D2] - Device release number: 0504
   0.216610     [D2] Trying to match device
   0.216618     [D2] match_function_subdriver (non-SHUT mode): matching a device...
   0.216627     [D2] match_function_subdriver (non-SHUT mode): failed to match a subdriver to vendor and/or product ID
   0.216635     [D2] Device does not match - skipping
   0.216648     [D2] Checking device (8087/800A) (001/002)
   0.283444     [D2] - VendorID: 8087
   0.283463     [D2] - ProductID: 800a
   0.283471     [D2] - Manufacturer: unknown
   0.283484     [D2] - Product: unknown
   0.283491     [D2] - Serial Number: unknown
   0.283498     [D2] - Bus: 001
   0.283505     [D2] - Device: 002
   0.283511     [D2] - Device release number: 0005
   0.283519     [D2] Trying to match device
   0.283524     [D2] match_function_subdriver (non-SHUT mode): matching a device...
   0.283534     [D2] match_function_subdriver (non-SHUT mode): failed to match a subdriver to vendor and/or product ID
   0.283540     [D2] Device does not match - skipping
   0.283552     [D2] Checking device (1D6B/0002) (001/001)
   0.283654     [D2] - VendorID: 1d6b
   0.283660     [D2] - ProductID: 0002
   0.283664     [D2] - Manufacturer: Linux 5.4.162-1-pve ehci_hcd
   0.283669     [D2] - Product: EHCI Host Controller
   0.283674     [D2] - Serial Number: 0000:00:1a.0
   0.283682     [D2] - Bus: 001
   0.283689     [D2] - Device: 001
   0.283696     [D2] - Device release number: 0504
   0.283707     [D2] Trying to match device
   0.283715     [D2] match_function_subdriver (non-SHUT mode): matching a device...
   0.283724     [D2] match_function_subdriver (non-SHUT mode): failed to match a subdriver to vendor and/or product ID
   0.283730     [D2] Device does not match - skipping
   0.283737     [D2] libusb0: No appropriate HID device found
   0.283750     No matching HID UPS found
```

```
root@PROXMOX:/usr/local/ups/bin# sudo ./upsc salicru@127.0.0.1 -u root
Error: Connection failure: Connection refused
root@PROXMOX:/usr/local/ups/bin#
```
```
root@PROXMOX:/usr/local/ups/bin# lsusb -v

.....
Bus 002 Device 010: ID 2e66:0201
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0
  bDeviceSubClass         0
  bDeviceProtocol         0
  bMaxPacketSize0         8
  idVendor           0x2e66
  idProduct          0x0201
  bcdDevice            1.29
  iManufacturer           1 Salicru
  iProduct                2 SLC TWIN PRO2<=3KVA
  iSerial                 4 232019D70264
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0022
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0
      bInterfaceProtocol      0
      iInterface              0
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength    1436
          Report Descriptor: (length is 1436)
            Item(Global): Usage Page, data= [ 0x84 ] 132
                            Power Device Page
            Item(Local ): Usage, data= [ 0x04 ] 4
                            UPS
            Item(Main  ): Collection, data= [ 0x01 ] 1
                            Application
            Item(Local ): Usage, data= [ 0x10 ] 16
                            Battery System
            Item(Main  ): Collection, data= [ 0x00 ] 0
                            Physical
            Item(Local ): Usage, data= [ 0x12 ] 18
                            Battery
            Item(Main  ): Collection, data= [ 0x00 ] 0
                            Physical
            Item(Local ): Usage, data= [ 0x13 ] 19
                            Battery ID
            Item(Global): Report ID, data= [ 0x20 ] 32
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x01 ] 1
            Item(Global): Logical Minimum, data= [ 0x00 ] 0
            Item(Global): Logical Maximum, data= [ 0xff 0x00 ] 255
            Item(Global): Unit, data= [ 0x00 ] 0
                            System: None, Unit: (None)
            Item(Global): Unit Exponent, data= [ 0x00 ] 0
                            Unit Exponent: 0
            Item(Main  ): Feature, data= [ 0x03 ] 3
                            Constant Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Global): Usage Page, data= [ 0xff 0xff ] 65535
                            (null)
            Item(Local ): Usage, data= [ 0x90 ] 144
                            (null)
            Item(Global): Report ID, data= [ 0x21 ] 33
            Item(Main  ): Feature, data= [ 0x82 ] 130
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Volatile Bitfield
            Item(Global): Usage Page, data= [ 0x84 ] 132
                            Power Device Page
            Item(Local ): Usage, data= [ 0x02 ] 2
                            Present Status
            Item(Main  ): Collection, data= [ 0x02 ] 2
                            Logical
            Item(Local ): Usage, data= [ 0x60 ] 96
                            Present
            Item(Global): Report ID, data= [ 0x27 ] 39
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Logical Maximum, data= [ 0xff 0x00 ] 255
            Item(Global): Unit, data= [ 0x00 ] 0
                            System: None, Unit: (None)
            Item(Main  ): Feature, data= [ 0x83 ] 131
                            Constant Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Volatile Bitfield
            Item(Local ): Usage, data= [ 0x60 ] 96
            ....
                            Preferred_State No_Null_Position Volatile Bitfield
            Item(Local ): Usage, data= [ 0xf1 ] 241
                            (null)
            Item(Global): Report ID, data= [ 0xf1 ] 241
            Item(Global): Report Count, data= [ 0x04 ] 4
            Item(Main  ): Feature, data= [ 0x82 ] 130
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Volatile Bitfield
            Item(Local ): Usage, data= [ 0xff ] 255
                            (null)
            Item(Global): Report ID, data= [ 0xff ] 255
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x01 ] 1
            Item(Global): Logical Minimum, data= [ 0x00 ] 0
            Item(Global): Logical Maximum, data= [ 0xff 0x00 ] 255
            Item(Global): Unit, data= [ 0x00 ] 0
                            System: None, Unit: (None)
            Item(Global): Unit Exponent, data= [ 0x00 ] 0
                            Unit Exponent: 0
            Item(Main  ): Feature, data= [ 0x82 ] 130
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Volatile Bitfield
            Item(Main  ): End Collection, data=none
            Item(Main  ): End Collection, data=none
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval              20
can't get device qualifier: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
Device Status:     0x0000
  (Bus Powered)

.......
```

```
root@PROXMOX:/usr/local/ups/bin# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

With debian package it just shows the message: "Driver failed to start". I assume it is due the debian package verison is outdated (2.7.4) so I tried to install from binaries with the otpion "--with-usb".

I  guess my main problem is related to the fact that driver can't find HID descriptor but I don't know how to continue from this point.

Can someone provide some tip please?

### PR DESCRIPTION
**Pull request by nbriggs**
The libusb 0.1 interface definition declares a (signed) char type for
control messages.  The HID descriptor length contained within a control
message is intended to be interpreted as a pair of unsigned bytes so
we must cast to uint8_t when doing the arithmetic rather than trip over
the sign bit.

Closes #1261, closes #1312.

### CODE REVIEW

**Comment by nbriggs** [comment]
Updated to fix same error a few lines later.

**Comment by nbriggs** [comment]
@jimklimov -- in looking at the code in libusb0.c to see why this happened, it looks as though the changes to introduce `usb_ctrl_charbuf` and friends and making them `char` for libusb-0.1, carefully undid the work to fix the libusb-0.1 API goof (see `typesafe_control_msg`) which is commented:
```
/* From usbutils: workaround libusb (0.1) API goofs:                                                                                                                                            
 * "byte" should never be sign extended;                                                                                                                                                        
 * using "char" is trouble.                                                                                                                                                                     
 * Likewise, sizes should never be negative.                                                                                                                                                    
 */
```
If the plan is to continue to support libusb-0.1 for any length of time I think it would make sense to revisit this.

**Comment by jimklimov** [comment]
Thanks for the work and analysis, and I agree that might be the troublesome
part. Currently changing jobs and computers, so was and will be a bit
semi-off-line for some days :\

File: drivers/libusb0.c [hunk 1]
```diff
@@ -377,7 +377,7 @@ static int libusb_open(usb_dev_handle **udevp,
 
 				upsdebug_hex(3, "HID descriptor, method 1", buf, 9);
 
-				rdlen1 = buf[7] | (buf[8] << 8);
+				rdlen1 = (uint8_t)buf[7] | ((uint8_t)buf[8] << 8);
```
Comment (jimklimov) [inline drivers/libusb0.c:380]: just wondering in hind-sight: is a `char << 8` safe on all platforms (to produce the high bits of a two-byte word here, I suppose) or would it result in a zero (all bits rotated from sight) or a same value (rotated around, ending where we started), or should there be more casting or similar magic here, to be portable?

Like `((uint16_t)buf[7] && 0x00FF) | (((uint16_t)buf[8] && 0x00FF) << 8)`

Comment (nbriggs) [reply drivers/libusb0.c:380]: The C integer type-promotion rules are not exactly obvious, but I think that [this StackOverflow article](https://stackoverflow.com/questions/46073295/implicit-type-promotion-rules) is an easier read than the actual spec, and quotes the spec.

To start, left shift, `<<` is *never* a circular shift.  `char << 8` (not unsigned char) is not going to produce the expected answer on any system that treats characters as signed.   For `char sc = 0x9a;`, `sc << 8` is 0xffff9a00.

Both `(uint16_t)` and `(uint8_t)` will be promoted to a larger unsigned type before the arithmetic is done -- but note that `(uint16_t) (char) 0x9a` is 0xff9a -- so you would be introducing trouble and then trying to compensate for it with the `& 0x00ff` instead of just saying what you mean with `(uint8_t)`.

The type of an integer constant (with no suffix, e.g. 256) is the first type into which the value will fit, see the list in https://en.cppreference.com/w/c/language/integer_constant -- so 256 is an **int** (not an **unsigned int**), but that won't matter in the case of `256 * (uint8_t)...` (but you'd get burned by `256 * (uint16_t)(char)`, see previous paragraph).   I believe it is going to do that arithmetic in an **int** sized container, so you'd have to think carefully if you were shifting left by 3 bytes with multiplication instead of 1 byte.

The net result is that I believe that the suggested change was both portable and quite clear about the programmers intent, without introducing new conversions which would require the reader to go back to the type promotion document.

Comments welcome...

Comment (nbriggs) [reply drivers/libusb0.c:380]: Or, to actually answer your final question:

> Or do the bit maths imply int anyway?

Yes, they do -- see this [copy of the C99 standard](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf) at the section "6.5.7 Bitwise shift operators" --
> Constraints
>    Each of the operands shall have integer type.
> Semantics
>    The integer promotions are performed on each of the operands. The type of the result is that of the promoted left operand.

Comment (jimklimov) [reply drivers/libusb0.c:380]: Thanks for the detailed reply, guess I was bitten a long time ago, maybe before C99 behavior was standardized across the board.

I followed up on this idea in #1325 so simplified it back (push pending); would extend the `make check` instead to make sure NUT builds, with whatever tools and CPUs build-systems use, do behave as we expect bit-wise.

Comment (nbriggs) [reply drivers/libusb0.c:380]: I went back and looked at the original K&R C book -- and it said
> The shift operators << and >> group left-to-righ.  Both perform the usual arithmetic conversions on their operands, each of which must be integral.  Then the right operand is converted to `int`; the type of the result is that of the left operand.

It goes on to say, of the results:
> The value of `E1<<E2` is E1 (interpreted as a bit pattern) left-shifted E2 bits; vacated bits are 0-filled.  The value of `E1 >>E2` is E1 right-shifted E2 bit positions.  The right shift is guaranteed to be logical (0-fill) if E1 is `unsigned`; otherwise it may be (and is, on the PDP-11) arithmetic (fill by a copy of the sign bit).

The _usual arithmetic conversions_ are defined this way (section 6.6):
>A great many operators cause conversions and yield result types in a similar way.  This pattern will be called the "usual arithmetic conversions."
First, any operands of type `char` or `short `are converted to `int`, and any of type `float` are converted to `double`.
Then, if either operand is `double`, the other is converted to `double` and that is the type of the result.
Otherwise, if either operand is `long`, the other is converted to long and that is the type of the result.
Otherwise, if either operand is `unsigned`, the other is converted to `unsigned` and that is the type of the result.
Otherwise, both operands must be `int`, and that is the type of the result.

About characters and integers it says (section 6.1):
> A character or or a short integer may be used wherever an integer may be used.  In all cases the value is converted to an integer.  Conversion of a shorter integer to a longer always involves sign extension; integers are signed quantities.  **Whether or not sign-extension occurs for characters is machine dependent,** but it is guaranteed that a member of the standard character set is non-negative.  Of the machines treated by this manual, only the PDP-11 sign-extends.  On the PDP-11, character variables range in value from -128 to 127; the characters of the ASCII alphabet are all positive.  A character constant specified with an ocatl escape suffers sign extension and may appear negative; for example, `'\377'` has the value -1.
When a longer integer is converted to a shorter or to a `char`, it is truncated on the left; excess bits are simply discarded.

If one were to read the section on type specifiers (section 8.2) it's not even clear that `unsigned char` was a legal declaration.   They finish up with Portability considerations (section 16)
>[...] Purely hardware issues like word size and the properties of floating point arithmetic and integer division have proven in practice to be not much of a problem. Other facets of the hardware are reflected in differing implementations.  **Some of these, particularly sign extensions (converting a negative character into a negative integer) and the order in which bytes are placed in a word, are a nuisance that must be carefully watched.**

When I was first writing code in C, for portability, we had to check the specific compiler & hardware combination to see how to define our own types in terms of the compiler/hardware supported types to get the behavior that we wanted -- at least now the standards give us `<stdint.h>` with `int8_t` and `uint8_t` types and it's the compiler writer's job to make them work correctly!
