### PR TITLE
Fix: tripplite_usb: if upsid is not specified, make any unit ID match

### LINKED ISSUE #2282: tripplite_usb: if `upsid` is not specified, any unit ID should match
It appears that between 2.8.0 and 746cb86110982920b9db8f5066b766d560d19eef (including 2.8.1), `tripplite_usb` stopped matching the default unit ID of 65535/0xffff when `upsid` is not specified in the configuration file.

Although I don't have hardware available to confirm, I suspect it is commit 106e7c6fe7, so I am tagging @sapireli.

IMHO, if `upsid` is not passed, then the matching function should still be `NULL` here: https://github.com/networkupstools/nut/commit/106e7c6fe7e0c67a7964e254ae8983f4537d8103#diff-51229908f9631058c142955b4726606c68b280194b6aeb184fdc9a17766f924eR1652

I would also recommend adding some logging during the matching process - the current debug message does not indicate that the ID doesn't match: https://github.com/networkupstools/nut/issues/2258#issuecomment-1912097611

### PR DESCRIPTION
**Pull request by sapireli**
small fix restoring matching when upsid is undefined in the ups.conf file closes #2282 as per the thread
cc @clepple

### CODE REVIEW

**Review by clepple — APPROVED** [review]
LGTM, thanks!

(note, I don't have hardware to test this, and I haven't looked at any build logs either)

File: drivers/tripplite_usb.c [hunk 1]
```diff
@@ -340,8 +340,11 @@ int match_by_unitid(usb_dev_handle *argudev, USBDevice_t *arghd, usb_ctrl_charbu
 	NUT_UNUSED_VARIABLE(rdbuf);
 	NUT_UNUSED_VARIABLE(rdlen);
 
-	/* Read ups id from the ups.conf */
-    if (value != NULL) {
+    /* If upsid is not defined in the config, return 1 (null behavior - match any device),
+	 * otherwise read it from the device and match against what was asked in ups.conf */
+    if (value == NULL) {
+        return 1;
+    } else {
```
Comment (jimklimov) [inline drivers/tripplite_usb.c:347]: I've updated the comment in code to better describe why we `return 1` - hopefully I got it right? ;)

The original wording did not seem unambiguous to me.

**Review by jimklimov — APPROVED** [review]
